//Template for stock information
export const stockInfo = [
  {
    ticker: "AAPL",
    image: "/assets/images/apple-logo.svg",
    company: "apple",
    prediction: "sell",
    percentage: "4.3%",
  },
  {
    ticker: "MSFT",
    image: "/assets/images/Microsoft-logo.svg",
    company: "Microsoft",
    prediction: "buy",
    percentage: "2.7%",
  },
  {
    ticker: "AMZN",
    image: "/assets/images/amazon-logo.svg",
    company: "Amazon",
    prediction: "sell",
    percentage: "1.2%",
  },
  {
    ticker: "META",
    image: "/assets/images/meta-logo.svg",
    company: "META",
    prediction: "buy",
    percentage: "7.5%",
  },
];

export const allStocks = [
  {
    ticker: "MMM",
    company: "3M",
    sector: "Industrials",
    image: "3m.svg",
    price: "159.38",
    prediction: "buy",
    lookup: "3m",
  },
  {
    ticker: "AOS",
    company: "A. O. Smith",
    sector: "Industrials",
    image: "ao-smith.png",
    price: "156.29",
    prediction: "buy",
    lookup: "a.-o.-smith",
  },
  {
    ticker: "ABT",
    company: "Abbott",
    sector: "Health Care",
    image: "abbott-laboratories.svg",
    price: "56.41",
    prediction: "buy",
    lookup: "abbott",
  },
  {
    ticker: "ABBV",
    company: "AbbVie",
    sector: "Health Care",
    image: "abbvie.svg",
    price: "40.4",
    prediction: "buy",
    lookup: "abbvie",
  },
  {
    ticker: "ACN",
    company: "Accenture",
    sector: "Information Technology",
    image: "accenture.svg",
    price: "171.88",
    prediction: "buy",
    lookup: "accenture",
  },
  {
    ticker: "ADBE",
    company: "Adobe Inc.",
    sector: "Information Technology",
    image: "adobe.svg",
    price: "174.89",
    prediction: "buy",
    lookup: "adobe-inc.",
  },
  {
    ticker: "AMD",
    company: "Advanced Micro Devices",
    sector: "Information Technology",
    image: "amd.svg",
    price: "165.73",
    prediction: "sell",
    lookup: "advanced-micro-devices",
  },
  {
    ticker: "AES",
    company: "AES Corporation",
    sector: "Utilities",
    image: "aes.svg",
    price: "37.57",
    prediction: "sell",
    lookup: "aes-corporation",
  },
  {
    ticker: "AFL",
    company: "Aflac",
    sector: "Financials",
    image: "aflac.png",
    price: "147.23",
    prediction: "sell",
    lookup: "aflac",
  },
  {
    ticker: "A",
    company: "Agilent Technologies",
    sector: "Health Care",
    image: "agilent-technologies.png",
    price: "199.72",
    prediction: "buy",
    lookup: "agilent-technologies",
  },
  {
    ticker: "APD",
    company: "Air Products and Chemicals",
    sector: "Materials",
    image: "air-products-and-chemicals.svg",
    price: "93.59",
    prediction: "sell",
    lookup: "air-products-and-chemicals",
  },
  {
    ticker: "ABNB",
    company: "Airbnb",
    sector: "Consumer Discretionary",
    image: "airbnb.svg",
    price: "130.23",
    prediction: "buy",
    lookup: "airbnb",
  },
  {
    ticker: "AKAM",
    company: "Akamai",
    sector: "Information Technology",
    image: "akamai.svg",
    price: "148.28",
    prediction: "sell",
    lookup: "akamai",
  },
  {
    ticker: "ALK",
    company: "Alaska Air Group",
    sector: "Industrials",
    image: "alaska-airlines.svg",
    price: "80.69",
    prediction: "buy",
    lookup: "alaska-air-group",
  },
  {
    ticker: "ALB",
    company: "Albemarle Corporation",
    sector: "Materials",
    image: "default.svg",
    price: "194.9",
    prediction: "sell",
    lookup: "albemarle-corporation",
  },
  {
    ticker: "ARE",
    company: "Alexandria Real Estate Equities",
    sector: "Real Estate",
    image: "alexandria-real-estate.png",
    price: "31.50",
    prediction: "buy",
    lookup: "alexandria-real-estate-equities",
  },
  {
    ticker: "ALGN",
    company: "Align Technology",
    sector: "Health Care",
    image: "align-technology.svg",
    price: "103.21",
    prediction: "buy",
    lookup: "align-technology",
  },
  {
    ticker: "ALLE",
    company: "Allegion",
    sector: "Industrials",
    image: "allegion.png",
    price: "30.95",
    prediction: "buy",
    lookup: "allegion",
  },
  {
    ticker: "LNT",
    company: "Alliant Energy",
    sector: "Utilities",
    image: "alliant-energy.png",
    price: "113.51",
    prediction: "sell",
    lookup: "alliant-energy",
  },
  {
    ticker: "ALL",
    company: "Allstate",
    sector: "Financials",
    image: "allstate.svg",
    price: "50.84",
    prediction: "sell",
    lookup: "allstate",
  },
  {
    ticker: "GOOGL",
    company: "Alphabet Inc. (Class A)",
    sector: "Communication Services",
    image: "alphabet-google.svg",
    price: "200.44",
    prediction: "sell",
    lookup: "alphabet-inc.-(class-a)",
  },
  {
    ticker: "GOOG",
    company: "Alphabet Inc. (Class C)",
    sector: "Communication Services",
    image: "default.svg",
    price: "83.62",
    prediction: "sell",
    lookup: "alphabet-inc.-(class-c)",
  },
  {
    ticker: "MO",
    company: "Altria",
    sector: "Consumer Staples",
    image: "altria-group.svg",
    price: "91.44",
    prediction: "sell",
    lookup: "altria",
  },
  {
    ticker: "AMZN",
    company: "Amazon",
    sector: "Consumer Discretionary",
    image: "amazon.svg",
    price: "118.35",
    prediction: "sell",
    lookup: "amazon",
  },
  {
    ticker: "AMCR",
    company: "Amcor",
    sector: "Materials",
    image: "amcor.png",
    price: "107.25",
    prediction: "sell",
    lookup: "amcor",
  },
  {
    ticker: "AEE",
    company: "Ameren",
    sector: "Utilities",
    image: "ameren.svg",
    price: "179.35",
    prediction: "sell",
    lookup: "ameren",
  },
  {
    ticker: "AAL",
    company: "American Airlines Group",
    sector: "Industrials",
    image: "american-airlines.svg",
    price: "154.82",
    prediction: "buy",
    lookup: "american-airlines-group",
  },
  {
    ticker: "AEP",
    company: "American Electric Power",
    sector: "Utilities",
    image: "american-electric-power.png",
    price: "135.81",
    prediction: "sell",
    lookup: "american-electric-power",
  },
  {
    ticker: "AXP",
    company: "American Express",
    sector: "Financials",
    image: "american-express.svg",
    price: "96.39",
    prediction: "sell",
    lookup: "american-express",
  },
  {
    ticker: "AIG",
    company: "American International Group",
    sector: "Financials",
    image: "aig.svg",
    price: "99.12",
    prediction: "buy",
    lookup: "american-international-group",
  },
  {
    ticker: "AMT",
    company: "American Tower",
    sector: "Real Estate",
    image: "american-tower.svg",
    price: "35.9",
    prediction: "sell",
    lookup: "american-tower",
  },
  {
    ticker: "AWK",
    company: "American Water Works",
    sector: "Utilities",
    image: "american-water-works.svg",
    price: "61.27",
    prediction: "buy",
    lookup: "american-water-works",
  },
  {
    ticker: "AMP",
    company: "Ameriprise Financial",
    sector: "Financials",
    image: "ameriprise-financial.svg",
    price: "168.37",
    prediction: "buy",
    lookup: "ameriprise-financial",
  },
  {
    ticker: "AME",
    company: "Ametek",
    sector: "Industrials",
    image: "ametek.svg",
    price: "63.57",
    prediction: "buy",
    lookup: "ametek",
  },
  {
    ticker: "AMGN",
    company: "Amgen",
    sector: "Health Care",
    image: "amgen.svg",
    price: "188.43",
    prediction: "buy",
    lookup: "amgen",
  },
  {
    ticker: "APH",
    company: "Amphenol",
    sector: "Information Technology",
    image: "amphenol.svg",
    price: "91.20",
    prediction: "sell",
    lookup: "amphenol",
  },
  {
    ticker: "ADI",
    company: "Analog Devices",
    sector: "Information Technology",
    image: "analog-devices.svg",
    price: "82.49",
    prediction: "buy",
    lookup: "analog-devices",
  },
  {
    ticker: "ANSS",
    company: "Ansys",
    sector: "Information Technology",
    image: "ansys.svg",
    price: "91.34",
    prediction: "sell",
    lookup: "ansys",
  },
  {
    ticker: "AON",
    company: "Aon",
    sector: "Financials",
    image: "aon.svg",
    price: "75.43",
    prediction: "sell",
    lookup: "aon",
  },
  {
    ticker: "APA",
    company: "APA Corporation",
    sector: "Energy",
    image: "default.svg",
    price: "109.45",
    prediction: "buy",
    lookup: "apa-corporation",
  },
  {
    ticker: "AAPL",
    company: "Apple Inc.",
    sector: "Information Technology",
    image: "apple.svg",
    price: "141.26",
    prediction: "buy",
    lookup: "apple-inc.",
  },
  {
    ticker: "AMAT",
    company: "Applied Materials",
    sector: "Information Technology",
    image: "applied-materials.svg",
    price: "83.73",
    prediction: "sell",
    lookup: "applied-materials",
  },
  {
    ticker: "APTV",
    company: "Aptiv",
    sector: "Consumer Discretionary",
    image: "aptiv.svg",
    price: "51.69",
    prediction: "sell",
    lookup: "aptiv",
  },
  {
    ticker: "ACGL",
    company: "Arch Capital Group",
    sector: "Financials",
    image: "arch-capital.svg",
    price: "175.40",
    prediction: "buy",
    lookup: "arch-capital-group",
  },
  {
    ticker: "ADM",
    company: "Archer-Daniels-Midland",
    sector: "Consumer Staples",
    image: "archer-daniels-midland.svg",
    price: "42.42",
    prediction: "sell",
    lookup: "archer-daniels-midland",
  },
  {
    ticker: "ANET",
    company: "Arista Networks",
    sector: "Information Technology",
    image: "arista-networks.svg",
    price: "174.47",
    prediction: "sell",
    lookup: "arista-networks",
  },
  {
    ticker: "AJG",
    company: "Arthur J. Gallagher & Co.",
    sector: "Financials",
    image: "default.svg",
    price: "62.22",
    prediction: "sell",
    lookup: "arthur-j.-gallagher-&-co.",
  },
  {
    ticker: "AIZ",
    company: "Assurant",
    sector: "Financials",
    image: "assurant.png",
    price: "98.67",
    prediction: "buy",
    lookup: "assurant",
  },
  {
    ticker: "T",
    company: "AT&T",
    sector: "Communication Services",
    image: "default.svg",
    price: "89.35",
    prediction: "buy",
    lookup: "at&t",
  },
  {
    ticker: "ATO",
    company: "Atmos Energy",
    sector: "Utilities",
    image: "atmos-energy.svg",
    price: "105.73",
    prediction: "sell",
    lookup: "atmos-energy",
  },
  {
    ticker: "ADSK",
    company: "Autodesk",
    sector: "Information Technology",
    image: "autodesk.svg",
    price: "118.61",
    prediction: "buy",
    lookup: "autodesk",
  },
  {
    ticker: "ADP",
    company: "Automated Data Processing",
    sector: "Industrials",
    image: "default.svg",
    price: "168.8",
    prediction: "buy",
    lookup: "automated-data-processing",
  },
  {
    ticker: "AZO",
    company: "AutoZone",
    sector: "Consumer Discretionary",
    image: "autozone.svg",
    price: "45.24",
    prediction: "sell",
    lookup: "autozone",
  },
  {
    ticker: "AVB",
    company: "AvalonBay Communities",
    sector: "Real Estate",
    image: "avalonbay-communities.svg",
    price: "61.37",
    prediction: "sell",
    lookup: "avalonbay-communities",
  },
  {
    ticker: "AVY",
    company: "Avery Dennison",
    sector: "Materials",
    image: "avery-dennison.png",
    price: "153.43",
    prediction: "buy",
    lookup: "avery-dennison",
  },
  {
    ticker: "AXON",
    company: "Axon Enterprise",
    sector: "Industrials",
    image: "axon.svg",
    price: "165.25",
    prediction: "sell",
    lookup: "axon-enterprise",
  },
  {
    ticker: "BKR",
    company: "Baker Hughes",
    sector: "Energy",
    image: "baker-hughes.svg",
    price: "188.74",
    prediction: "sell",
    lookup: "baker-hughes",
  },
  {
    ticker: "BALL",
    company: "Ball Corporation",
    sector: "Materials",
    image: "ball-corporation.svg",
    price: "100.64",
    prediction: "sell",
    lookup: "ball-corporation",
  },
  {
    ticker: "BAC",
    company: "Bank of America",
    sector: "Financials",
    image: "bank-of-america.svg",
    price: "112.62",
    prediction: "buy",
    lookup: "bank-of-america",
  },
  {
    ticker: "BK",
    company: "Bank of New York Mellon",
    sector: "Financials",
    image: "bny-mellon.svg",
    price: "121.12",
    prediction: "buy",
    lookup: "bank-of-new-york-mellon",
  },
  {
    ticker: "BBWI",
    company: "Bath & Body Works, Inc.",
    sector: "Consumer Discretionary",
    image: "bath-body-works.svg",
    price: "197.99",
    prediction: "sell",
    lookup: "bath-&-body-works,-inc.",
  },
  {
    ticker: "BAX",
    company: "Baxter International",
    sector: "Health Care",
    image: "baxter.svg",
    price: "69.10",
    prediction: "sell",
    lookup: "baxter-international",
  },
  {
    ticker: "BDX",
    company: "Becton Dickinson",
    sector: "Health Care",
    image: "becton-dickinson.svg",
    price: "116.30",
    prediction: "sell",
    lookup: "becton-dickinson",
  },
  {
    ticker: "BRK.B",
    company: "Berkshire Hathaway",
    sector: "Financials",
    image: "berkshire-hathaway.svg",
    price: "32.6",
    prediction: "buy",
    lookup: "berkshire-hathaway",
  },
  {
    ticker: "BBY",
    company: "Best Buy",
    sector: "Consumer Discretionary",
    image: "best-buy.svg",
    price: "102.23",
    prediction: "buy",
    lookup: "best-buy",
  },
  {
    ticker: "BIO",
    company: "Bio-Rad",
    sector: "Health Care",
    image: "default.svg",
    price: "72.55",
    prediction: "sell",
    lookup: "bio-rad",
  },
  {
    ticker: "TECH",
    company: "Bio-Techne",
    sector: "Health Care",
    image: "bio-techne.svg",
    price: "55.45",
    prediction: "sell",
    lookup: "bio-techne",
  },
  {
    ticker: "BIIB",
    company: "Biogen",
    sector: "Health Care",
    image: "biogen.svg",
    price: "53.37",
    prediction: "buy",
    lookup: "biogen",
  },
  {
    ticker: "BLK",
    company: "BlackRock",
    sector: "Financials",
    image: "blackrock.svg",
    price: "41.55",
    prediction: "sell",
    lookup: "blackrock",
  },
  {
    ticker: "BX",
    company: "Blackstone",
    sector: "Financials",
    image: "blackstone-group.svg",
    price: "178.74",
    prediction: "buy",
    lookup: "blackstone",
  },
  {
    ticker: "BA",
    company: "Boeing",
    sector: "Industrials",
    image: "boeing.svg",
    price: "99.18",
    prediction: "buy",
    lookup: "boeing",
  },
  {
    ticker: "BKNG",
    company: "Booking Holdings",
    sector: "Consumer Discretionary",
    image: "booking-holdings.svg",
    price: "161.69",
    prediction: "sell",
    lookup: "booking-holdings",
  },
  {
    ticker: "BWA",
    company: "BorgWarner",
    sector: "Consumer Discretionary",
    image: "borgwarner.svg",
    price: "90.77",
    prediction: "sell",
    lookup: "borgwarner",
  },
  {
    ticker: "BXP",
    company: "Boston Properties",
    sector: "Real Estate",
    image: "boston-properties.svg",
    price: "179.89",
    prediction: "buy",
    lookup: "boston-properties",
  },
  {
    ticker: "BSX",
    company: "Boston Scientific",
    sector: "Health Care",
    image: "boston-scientific.svg",
    price: "146.99",
    prediction: "buy",
    lookup: "boston-scientific",
  },
  {
    ticker: "BMY",
    company: "Bristol Myers Squibb",
    sector: "Health Care",
    image: "bristol-myers-squibb.svg",
    price: "88.70",
    prediction: "sell",
    lookup: "bristol-myers-squibb",
  },
  {
    ticker: "AVGO",
    company: "Broadcom Inc.",
    sector: "Information Technology",
    image: "broadcom.svg",
    price: "31.78",
    prediction: "sell",
    lookup: "broadcom-inc.",
  },
  {
    ticker: "BR",
    company: "Broadridge Financial Solutions",
    sector: "Industrials",
    image: "broadridge-financial-solutions.svg",
    price: "186.38",
    prediction: "sell",
    lookup: "broadridge-financial-solutions",
  },
  {
    ticker: "BRO",
    company: "Brown & Brown",
    sector: "Financials",
    image: "brown-and-brown.svg",
    price: "94.33",
    prediction: "buy",
    lookup: "brown-&-brown",
  },
  {
    ticker: "BF.B",
    company: "Brown\u00e2\u20ac\u201cForman",
    sector: "Consumer Staples",
    image: "brown-forman.svg",
    price: "139.64",
    prediction: "sell",
    lookup: "brown\u00e2\u20ac\u201cforman",
  },
  {
    ticker: "BG",
    company: "Bunge Global SA",
    sector: "Consumer Staples",
    image: "bunge.svg",
    price: "37.85",
    prediction: "buy",
    lookup: "bunge-global-sa",
  },
  {
    ticker: "CDNS",
    company: "Cadence Design Systems",
    sector: "Information Technology",
    image: "cadence-design-systems.svg",
    price: "176.97",
    prediction: "sell",
    lookup: "cadence-design-systems",
  },
  {
    ticker: "CZR",
    company: "Caesars Entertainment",
    sector: "Consumer Discretionary",
    image: "caesars-entertainment.svg",
    price: "194.27",
    prediction: "buy",
    lookup: "caesars-entertainment",
  },
  {
    ticker: "CPT",
    company: "Camden Property Trust",
    sector: "Real Estate",
    image: "camden-property-trust.svg",
    price: "84.54",
    prediction: "sell",
    lookup: "camden-property-trust",
  },
  {
    ticker: "CPB",
    company: "Campbell Soup Company",
    sector: "Consumer Staples",
    image: "campbell-soup.svg",
    price: "93.94",
    prediction: "buy",
    lookup: "campbell-soup-company",
  },
  {
    ticker: "COF",
    company: "Capital One",
    sector: "Financials",
    image: "capital-one.svg",
    price: "48.52",
    prediction: "buy",
    lookup: "capital-one",
  },
  {
    ticker: "CAH",
    company: "Cardinal Health",
    sector: "Health Care",
    image: "cardinal-health.svg",
    price: "190.7",
    prediction: "buy",
    lookup: "cardinal-health",
  },
  {
    ticker: "KMX",
    company: "CarMax",
    sector: "Consumer Discretionary",
    image: "carmax.svg",
    price: "40.26",
    prediction: "buy",
    lookup: "carmax",
  },
  {
    ticker: "CCL",
    company: "Carnival",
    sector: "Consumer Discretionary",
    image: "carnival-cruise-line.svg",
    price: "104.56",
    prediction: "buy",
    lookup: "carnival",
  },
  {
    ticker: "CARR",
    company: "Carrier Global",
    sector: "Industrials",
    image: "carrier.svg",
    price: "171.90",
    prediction: "sell",
    lookup: "carrier-global",
  },
  {
    ticker: "CTLT",
    company: "Catalent",
    sector: "Health Care",
    image: "catalent.svg",
    price: "98.70",
    prediction: "sell",
    lookup: "catalent",
  },
  {
    ticker: "CAT",
    company: "Caterpillar Inc.",
    sector: "Industrials",
    image: "caterpillar.svg",
    price: "141.65",
    prediction: "sell",
    lookup: "caterpillar-inc.",
  },
  {
    ticker: "CBOE",
    company: "Cboe Global Markets",
    sector: "Financials",
    image: "cboe.svg",
    price: "107.91",
    prediction: "buy",
    lookup: "cboe-global-markets",
  },
  {
    ticker: "CBRE",
    company: "CBRE Group",
    sector: "Real Estate",
    image: "cbre-group.svg",
    price: "151.53",
    prediction: "sell",
    lookup: "cbre-group",
  },
  {
    ticker: "CDW",
    company: "CDW",
    sector: "Information Technology",
    image: "cdw-corporation.svg",
    price: "127.32",
    prediction: "sell",
    lookup: "cdw",
  },
  {
    ticker: "CE",
    company: "Celanese",
    sector: "Materials",
    image: "celanese.svg",
    price: "149.89",
    prediction: "sell",
    lookup: "celanese",
  },
  {
    ticker: "COR",
    company: "Cencora",
    sector: "Health Care",
    image: "cencora.svg",
    price: "71.95",
    prediction: "buy",
    lookup: "cencora",
  },
  {
    ticker: "CNC",
    company: "Centene Corporation",
    sector: "Health Care",
    image: "centene.svg",
    price: "188.89",
    prediction: "sell",
    lookup: "centene-corporation",
  },
  {
    ticker: "CNP",
    company: "CenterPoint Energy",
    sector: "Utilities",
    image: "centerpoint-energy.svg",
    price: "63.26",
    prediction: "sell",
    lookup: "centerpoint-energy",
  },
  {
    ticker: "CDAY",
    company: "Ceridian",
    sector: "Industrials",
    image: "ceridian.png",
    price: "104.38",
    prediction: "buy",
    lookup: "ceridian",
  },
  {
    ticker: "CF",
    company: "CF Industries",
    sector: "Materials",
    image: "cf-industries.svg",
    price: "148.94",
    prediction: "sell",
    lookup: "cf-industries",
  },
  {
    ticker: "CHRW",
    company: "CH Robinson",
    sector: "Industrials",
    image: "ch-robinson.svg",
    price: "32.86",
    prediction: "buy",
    lookup: "ch-robinson",
  },
  {
    ticker: "CRL",
    company: "Charles River Laboratories",
    sector: "Health Care",
    image: "default.svg",
    price: "112.58",
    prediction: "sell",
    lookup: "charles-river-laboratories",
  },
  {
    ticker: "SCHW",
    company: "Charles Schwab Corporation",
    sector: "Financials",
    image: "charles-schwab.svg",
    price: "191.86",
    prediction: "sell",
    lookup: "charles-schwab-corporation",
  },
  {
    ticker: "CHTR",
    company: "Charter Communications",
    sector: "Communication Services",
    image: "charter-communications.svg",
    price: "92.58",
    prediction: "sell",
    lookup: "charter-communications",
  },
  {
    ticker: "CVX",
    company: "Chevron Corporation",
    sector: "Energy",
    image: "chevron.svg",
    price: "135.96",
    prediction: "buy",
    lookup: "chevron-corporation",
  },
  {
    ticker: "CMG",
    company: "Chipotle Mexican Grill",
    sector: "Consumer Discretionary",
    image: "chipotle-mexican-grill.svg",
    price: "128.51",
    prediction: "sell",
    lookup: "chipotle-mexican-grill",
  },
  {
    ticker: "CB",
    company: "Chubb Limited",
    sector: "Financials",
    image: "chubb.svg",
    price: "119.95",
    prediction: "sell",
    lookup: "chubb-limited",
  },
  {
    ticker: "CHD",
    company: "Church & Dwight",
    sector: "Consumer Staples",
    image: "church-and-dwight.png",
    price: "66.4",
    prediction: "buy",
    lookup: "church-&-dwight",
  },
  {
    ticker: "CI",
    company: "Cigna",
    sector: "Health Care",
    image: "cigna.svg",
    price: "193.72",
    prediction: "buy",
    lookup: "cigna",
  },
  {
    ticker: "CINF",
    company: "Cincinnati Financial",
    sector: "Financials",
    image: "default.svg",
    price: "103.16",
    prediction: "sell",
    lookup: "cincinnati-financial",
  },
  {
    ticker: "CTAS",
    company: "Cintas",
    sector: "Industrials",
    image: "cintas.svg",
    price: "76.63",
    prediction: "buy",
    lookup: "cintas",
  },
  {
    ticker: "CSCO",
    company: "Cisco",
    sector: "Information Technology",
    image: "cisco.svg",
    price: "104.23",
    prediction: "buy",
    lookup: "cisco",
  },
  {
    ticker: "C",
    company: "Citigroup",
    sector: "Financials",
    image: "citigroup.svg",
    price: "115.44",
    prediction: "sell",
    lookup: "citigroup",
  },
  {
    ticker: "CFG",
    company: "Citizens Financial Group",
    sector: "Financials",
    image: "citizens-financial-group.svg",
    price: "114.12",
    prediction: "buy",
    lookup: "citizens-financial-group",
  },
  {
    ticker: "CLX",
    company: "Clorox",
    sector: "Consumer Staples",
    image: "clorox.svg",
    price: "70.29",
    prediction: "sell",
    lookup: "clorox",
  },
  {
    ticker: "CME",
    company: "CME Group",
    sector: "Financials",
    image: "cme-group.svg",
    price: "193.54",
    prediction: "buy",
    lookup: "cme-group",
  },
  {
    ticker: "CMS",
    company: "CMS Energy",
    sector: "Utilities",
    image: "cms-energy.svg",
    price: "128.65",
    prediction: "buy",
    lookup: "cms-energy",
  },
  {
    ticker: "KO",
    company: "Coca-Cola Company (The)",
    sector: "Consumer Staples",
    image: "default.svg",
    price: "73.74",
    prediction: "sell",
    lookup: "coca-cola-company-(the)",
  },
  {
    ticker: "CTSH",
    company: "Cognizant",
    sector: "Information Technology",
    image: "cognizant-technology-solutions.svg",
    price: "150.90",
    prediction: "sell",
    lookup: "cognizant",
  },
  {
    ticker: "CL",
    company: "Colgate-Palmolive",
    sector: "Consumer Staples",
    image: "colgate-palmolive.svg",
    price: "84.51",
    prediction: "buy",
    lookup: "colgate-palmolive",
  },
  {
    ticker: "CMCSA",
    company: "Comcast",
    sector: "Communication Services",
    image: "comcast.svg",
    price: "89.61",
    prediction: "buy",
    lookup: "comcast",
  },
  {
    ticker: "CMA",
    company: "Comerica",
    sector: "Financials",
    image: "comerica.svg",
    price: "52.89",
    prediction: "sell",
    lookup: "comerica",
  },
  {
    ticker: "CAG",
    company: "Conagra Brands",
    sector: "Consumer Staples",
    image: "default.svg",
    price: "118.65",
    prediction: "buy",
    lookup: "conagra-brands",
  },
  {
    ticker: "COP",
    company: "ConocoPhillips",
    sector: "Energy",
    image: "conocophillips.svg",
    price: "56.77",
    prediction: "buy",
    lookup: "conocophillips",
  },
  {
    ticker: "ED",
    company: "Consolidated Edison",
    sector: "Utilities",
    image: "consolidated-edison.svg",
    price: "193.88",
    prediction: "buy",
    lookup: "consolidated-edison",
  },
  {
    ticker: "STZ",
    company: "Constellation Brands",
    sector: "Consumer Staples",
    image: "constellation-brands.svg",
    price: "158.46",
    prediction: "buy",
    lookup: "constellation-brands",
  },
  {
    ticker: "CEG",
    company: "Constellation Energy",
    sector: "Utilities",
    image: "constellation-energy.svg",
    price: "49.0",
    prediction: "buy",
    lookup: "constellation-energy",
  },
  {
    ticker: "COO",
    company: "CooperCompanies",
    sector: "Health Care",
    image: "default.svg",
    price: "144.33",
    prediction: "sell",
    lookup: "coopercompanies",
  },
  {
    ticker: "CPRT",
    company: "Copart",
    sector: "Industrials",
    image: "copart.svg",
    price: "137.66",
    prediction: "buy",
    lookup: "copart",
  },
  {
    ticker: "GLW",
    company: "Corning Inc.",
    sector: "Information Technology",
    image: "corning.svg",
    price: "67.60",
    prediction: "buy",
    lookup: "corning-inc.",
  },
  {
    ticker: "CTVA",
    company: "Corteva",
    sector: "Materials",
    image: "corteva.svg",
    price: "82.29",
    prediction: "buy",
    lookup: "corteva",
  },
  {
    ticker: "CSGP",
    company: "CoStar Group",
    sector: "Real Estate",
    image: "costar-group.svg",
    price: "173.69",
    prediction: "buy",
    lookup: "costar-group",
  },
  {
    ticker: "COST",
    company: "Costco",
    sector: "Consumer Staples",
    image: "costco.svg",
    price: "151.29",
    prediction: "sell",
    lookup: "costco",
  },
  {
    ticker: "CTRA",
    company: "Coterra",
    sector: "Energy",
    image: "coterra-energy.svg",
    price: "31.0",
    prediction: "sell",
    lookup: "coterra",
  },
  {
    ticker: "CCI",
    company: "Crown Castle",
    sector: "Real Estate",
    image: "crown-castle.svg",
    price: "42.82",
    prediction: "buy",
    lookup: "crown-castle",
  },
  {
    ticker: "CSX",
    company: "CSX",
    sector: "Industrials",
    image: "csx-corporation.svg",
    price: "71.5",
    prediction: "sell",
    lookup: "csx",
  },
  {
    ticker: "CMI",
    company: "Cummins",
    sector: "Industrials",
    image: "cummins.svg",
    price: "96.10",
    prediction: "sell",
    lookup: "cummins",
  },
  {
    ticker: "CVS",
    company: "CVS Health",
    sector: "Health Care",
    image: "cvs-health.svg",
    price: "167.59",
    prediction: "sell",
    lookup: "cvs-health",
  },
  {
    ticker: "DHR",
    company: "Danaher Corporation",
    sector: "Health Care",
    image: "danaher.svg",
    price: "144.19",
    prediction: "sell",
    lookup: "danaher-corporation",
  },
  {
    ticker: "DRI",
    company: "Darden Restaurants",
    sector: "Consumer Discretionary",
    image: "darden-restaurants.svg",
    price: "198.84",
    prediction: "buy",
    lookup: "darden-restaurants",
  },
  {
    ticker: "DVA",
    company: "DaVita Inc.",
    sector: "Health Care",
    image: "davita.svg",
    price: "94.62",
    prediction: "sell",
    lookup: "davita-inc.",
  },
  {
    ticker: "DE",
    company: "John Deere",
    sector: "Industrials",
    image: "deere-company.svg",
    price: "74.41",
    prediction: "buy",
    lookup: "john-deere",
  },
  {
    ticker: "DAL",
    company: "Delta Air Lines",
    sector: "Industrials",
    image: "delta-air-lines.svg",
    price: "170.89",
    prediction: "buy",
    lookup: "delta-air-lines",
  },
  {
    ticker: "XRAY",
    company: "Dentsply Sirona",
    sector: "Health Care",
    image: "dentsply-sirona.svg",
    price: "69.2",
    prediction: "sell",
    lookup: "dentsply-sirona",
  },
  {
    ticker: "DVN",
    company: "Devon Energy",
    sector: "Energy",
    image: "devon-energy.svg",
    price: "104.18",
    prediction: "sell",
    lookup: "devon-energy",
  },
  {
    ticker: "DXCM",
    company: "Dexcom",
    sector: "Health Care",
    image: "dexcom.svg",
    price: "60.78",
    prediction: "sell",
    lookup: "dexcom",
  },
  {
    ticker: "FANG",
    company: "Diamondback Energy",
    sector: "Energy",
    image: "diamondback-energy.svg",
    price: "103.61",
    prediction: "buy",
    lookup: "diamondback-energy",
  },
  {
    ticker: "DLR",
    company: "Digital Realty",
    sector: "Real Estate",
    image: "digital-realty.svg",
    price: "122.40",
    prediction: "buy",
    lookup: "digital-realty",
  },
  {
    ticker: "DFS",
    company: "Discover Financial",
    sector: "Financials",
    image: "discover-financial-services.svg",
    price: "44.92",
    prediction: "buy",
    lookup: "discover-financial",
  },
  {
    ticker: "DG",
    company: "Dollar General",
    sector: "Consumer Staples",
    image: "dollar-general.png",
    price: "36.45",
    prediction: "buy",
    lookup: "dollar-general",
  },
  {
    ticker: "DLTR",
    company: "Dollar Tree",
    sector: "Consumer Staples",
    image: "dollar-tree.svg",
    price: "101.37",
    prediction: "sell",
    lookup: "dollar-tree",
  },
  {
    ticker: "D",
    company: "Dominion Energy",
    sector: "Utilities",
    image: "dominion-energy.svg",
    price: "161.39",
    prediction: "sell",
    lookup: "dominion-energy",
  },
  {
    ticker: "DPZ",
    company: "Domino's",
    sector: "Consumer Discretionary",
    image: "dominos-pizza.svg",
    price: "124.0",
    prediction: "buy",
    lookup: "domino's",
  },
  {
    ticker: "DOV",
    company: "Dover Corporation",
    sector: "Industrials",
    image: "dover.svg",
    price: "128.60",
    prediction: "sell",
    lookup: "dover-corporation",
  },
  {
    ticker: "DOW",
    company: "Dow Inc.",
    sector: "Materials",
    image: "dow.svg",
    price: "106.34",
    prediction: "sell",
    lookup: "dow-inc.",
  },
  {
    ticker: "DHI",
    company: "DR Horton",
    sector: "Consumer Discretionary",
    image: "dr-horton.svg",
    price: "89.36",
    prediction: "sell",
    lookup: "dr-horton",
  },
  {
    ticker: "DTE",
    company: "DTE Energy",
    sector: "Utilities",
    image: "dte-energy.svg",
    price: "141.12",
    prediction: "sell",
    lookup: "dte-energy",
  },
  {
    ticker: "DUK",
    company: "Duke Energy",
    sector: "Utilities",
    image: "duke-energy.png",
    price: "133.49",
    prediction: "buy",
    lookup: "duke-energy",
  },
  {
    ticker: "DD",
    company: "DuPont",
    sector: "Materials",
    image: "dupont-de-nemours.svg",
    price: "126.61",
    prediction: "buy",
    lookup: "dupont",
  },
  {
    ticker: "EMN",
    company: "Eastman Chemical Company",
    sector: "Materials",
    image: "eastman-chemical.svg",
    price: "41.79",
    prediction: "sell",
    lookup: "eastman-chemical-company",
  },
  {
    ticker: "ETN",
    company: "Eaton Corporation",
    sector: "Industrials",
    image: "eaton.svg",
    price: "115.20",
    prediction: "buy",
    lookup: "eaton-corporation",
  },
  {
    ticker: "EBAY",
    company: "eBay",
    sector: "Consumer Discretionary",
    image: "ebay.svg",
    price: "155.98",
    prediction: "sell",
    lookup: "ebay",
  },
  {
    ticker: "ECL",
    company: "Ecolab",
    sector: "Materials",
    image: "ecolab.svg",
    price: "98.23",
    prediction: "buy",
    lookup: "ecolab",
  },
  {
    ticker: "EIX",
    company: "Edison International",
    sector: "Utilities",
    image: "edison-international.svg",
    price: "126.66",
    prediction: "sell",
    lookup: "edison-international",
  },
  {
    ticker: "EW",
    company: "Edwards Lifesciences",
    sector: "Health Care",
    image: "edwards-lifesciences.svg",
    price: "189.81",
    prediction: "buy",
    lookup: "edwards-lifesciences",
  },
  {
    ticker: "EA",
    company: "Electronic Arts",
    sector: "Communication Services",
    image: "electronic-arts.svg",
    price: "124.35",
    prediction: "buy",
    lookup: "electronic-arts",
  },
  {
    ticker: "ELV",
    company: "Elevance Health",
    sector: "Health Care",
    image: "elevance-health.svg",
    price: "160.39",
    prediction: "sell",
    lookup: "elevance-health",
  },
  {
    ticker: "LLY",
    company: "Eli Lilly and Company",
    sector: "Health Care",
    image: "eli-lilly.svg",
    price: "73.43",
    prediction: "sell",
    lookup: "eli-lilly-and-company",
  },
  {
    ticker: "EMR",
    company: "Emerson Electric",
    sector: "Industrials",
    image: "emerson.svg",
    price: "85.90",
    prediction: "buy",
    lookup: "emerson-electric",
  },
  {
    ticker: "ENPH",
    company: "Enphase",
    sector: "Information Technology",
    image: "enphase-energy.svg",
    price: "108.69",
    prediction: "sell",
    lookup: "enphase",
  },
  {
    ticker: "ETR",
    company: "Entergy",
    sector: "Utilities",
    image: "entergy.svg",
    price: "92.90",
    prediction: "buy",
    lookup: "entergy",
  },
  {
    ticker: "EOG",
    company: "EOG Resources",
    sector: "Energy",
    image: "eog-resources.svg",
    price: "41.84",
    prediction: "sell",
    lookup: "eog-resources",
  },
  {
    ticker: "EPAM",
    company: "EPAM Systems",
    sector: "Information Technology",
    image: "epam-systems.svg",
    price: "76.31",
    prediction: "buy",
    lookup: "epam-systems",
  },
  {
    ticker: "EQT",
    company: "EQT",
    sector: "Energy",
    image: "eqt.svg",
    price: "177.58",
    prediction: "buy",
    lookup: "eqt",
  },
  {
    ticker: "EFX",
    company: "Equifax",
    sector: "Industrials",
    image: "equifax.svg",
    price: "182.38",
    prediction: "sell",
    lookup: "equifax",
  },
  {
    ticker: "EQIX",
    company: "Equinix",
    sector: "Real Estate",
    image: "equinix.svg",
    price: "113.29",
    prediction: "buy",
    lookup: "equinix",
  },
  {
    ticker: "EQR",
    company: "Equity Residential",
    sector: "Real Estate",
    image: "equity-residential.svg",
    price: "171.33",
    prediction: "sell",
    lookup: "equity-residential",
  },
  {
    ticker: "ESS",
    company: "Essex Property Trust",
    sector: "Real Estate",
    image: "essex-property-trust.svg",
    price: "170.94",
    prediction: "buy",
    lookup: "essex-property-trust",
  },
  {
    ticker: "EL",
    company: "Est\u00c3\u00a9e Lauder Companies (The)",
    sector: "Consumer Staples",
    image: "estee-lauder.svg",
    price: "146.77",
    prediction: "buy",
    lookup: "est\u00e3\u00a9e-lauder-companies-(the)",
  },
  {
    ticker: "ETSY",
    company: "Etsy",
    sector: "Consumer Discretionary",
    image: "etsy.svg",
    price: "162.50",
    prediction: "sell",
    lookup: "etsy",
  },
  {
    ticker: "EG",
    company: "Everest Re",
    sector: "Financials",
    image: "everest-re.svg",
    price: "190.78",
    prediction: "buy",
    lookup: "everest-re",
  },
  {
    ticker: "EVRG",
    company: "Evergy",
    sector: "Utilities",
    image: "evergy.svg",
    price: "114.78",
    prediction: "sell",
    lookup: "evergy",
  },
  {
    ticker: "ES",
    company: "Eversource",
    sector: "Utilities",
    image: "eversource-energy.svg",
    price: "127.5",
    prediction: "buy",
    lookup: "eversource",
  },
  {
    ticker: "EXC",
    company: "Exelon",
    sector: "Utilities",
    image: "exelon-corporation.svg",
    price: "143.64",
    prediction: "sell",
    lookup: "exelon",
  },
  {
    ticker: "EXPE",
    company: "Expedia Group",
    sector: "Consumer Discretionary",
    image: "expedia.svg",
    price: "163.33",
    prediction: "sell",
    lookup: "expedia-group",
  },
  {
    ticker: "EXPD",
    company: "Expeditors International",
    sector: "Industrials",
    image: "expeditors.svg",
    price: "56.86",
    prediction: "sell",
    lookup: "expeditors-international",
  },
  {
    ticker: "EXR",
    company: "Extra Space Storage",
    sector: "Real Estate",
    image: "extra-space-storage.svg",
    price: "33.14",
    prediction: "sell",
    lookup: "extra-space-storage",
  },
  {
    ticker: "XOM",
    company: "ExxonMobil",
    sector: "Energy",
    image: "exxon-mobil.svg",
    price: "174.1",
    prediction: "buy",
    lookup: "exxonmobil",
  },
  {
    ticker: "FFIV",
    company: "F5, Inc.",
    sector: "Information Technology",
    image: "f5-networks.svg",
    price: "135.67",
    prediction: "sell",
    lookup: "f5,-inc.",
  },
  {
    ticker: "FDS",
    company: "FactSet",
    sector: "Financials",
    image: "factset.svg",
    price: "120.57",
    prediction: "buy",
    lookup: "factset",
  },
  {
    ticker: "FICO",
    company: "Fair Isaac",
    sector: "Information Technology",
    image: "fico.svg",
    price: "51.73",
    prediction: "sell",
    lookup: "fair-isaac",
  },
  {
    ticker: "FAST",
    company: "Fastenal",
    sector: "Industrials",
    image: "fastenal.svg",
    price: "115.16",
    prediction: "sell",
    lookup: "fastenal",
  },
  {
    ticker: "FRT",
    company: "Federal Realty",
    sector: "Real Estate",
    image: "federal-realty-investment-trust.svg",
    price: "95.72",
    prediction: "sell",
    lookup: "federal-realty",
  },
  {
    ticker: "FDX",
    company: "FedEx",
    sector: "Industrials",
    image: "fedex.svg",
    price: "55.0",
    prediction: "sell",
    lookup: "fedex",
  },
  {
    ticker: "FIS",
    company: "Fidelity National Information Services",
    sector: "Financials",
    image: "fidelity-national-information-services.svg",
    price: "80.11",
    prediction: "sell",
    lookup: "fidelity-national-information-services",
  },
  {
    ticker: "FITB",
    company: "Fifth Third Bank",
    sector: "Financials",
    image: "fifth-third-bank.svg",
    price: "180.79",
    prediction: "sell",
    lookup: "fifth-third-bank",
  },
  {
    ticker: "FSLR",
    company: "First Solar",
    sector: "Information Technology",
    image: "first-solar.svg",
    price: "42.69",
    prediction: "sell",
    lookup: "first-solar",
  },
  {
    ticker: "FE",
    company: "FirstEnergy",
    sector: "Utilities",
    image: "firstenergy.svg",
    price: "77.12",
    prediction: "buy",
    lookup: "firstenergy",
  },
  {
    ticker: "FI",
    company: "Fiserv",
    sector: "Financials",
    image: "fiserv.svg",
    price: "165.15",
    prediction: "buy",
    lookup: "fiserv",
  },
  {
    ticker: "FLT",
    company: "Fleetcor",
    sector: "Financials",
    image: "fleetcor.svg",
    price: "127.58",
    prediction: "buy",
    lookup: "fleetcor",
  },
  {
    ticker: "FMC",
    company: "FMC Corporation",
    sector: "Materials",
    image: "fmc.svg",
    price: "38.12",
    prediction: "sell",
    lookup: "fmc-corporation",
  },
  {
    ticker: "F",
    company: "Ford Motor Company",
    sector: "Consumer Discretionary",
    image: "ford.svg",
    price: "112.96",
    prediction: "sell",
    lookup: "ford-motor-company",
  },
  {
    ticker: "FTNT",
    company: "Fortinet",
    sector: "Information Technology",
    image: "fortinet.svg",
    price: "41.18",
    prediction: "sell",
    lookup: "fortinet",
  },
  {
    ticker: "FTV",
    company: "Fortive",
    sector: "Industrials",
    image: "fortive.svg",
    price: "115.91",
    prediction: "buy",
    lookup: "fortive",
  },
  {
    ticker: "FOXA",
    company: "Fox Corporation (Class A)",
    sector: "Communication Services",
    image: "default.svg",
    price: "138.27",
    prediction: "sell",
    lookup: "fox-corporation-(class-a)",
  },
  {
    ticker: "FOX",
    company: "Fox Corporation (Class B)",
    sector: "Communication Services",
    image: "fox-corporation.svg",
    price: "84.71",
    prediction: "sell",
    lookup: "fox-corporation-(class-b)",
  },
  {
    ticker: "BEN",
    company: "Franklin Templeton",
    sector: "Financials",
    image: "default.svg",
    price: "152.51",
    prediction: "buy",
    lookup: "franklin-templeton",
  },
  {
    ticker: "FCX",
    company: "Freeport-McMoRan",
    sector: "Materials",
    image: "freeport-mcmoran.svg",
    price: "104.89",
    prediction: "sell",
    lookup: "freeport-mcmoran",
  },
  {
    ticker: "GRMN",
    company: "Garmin",
    sector: "Consumer Discretionary",
    image: "garmin.svg",
    price: "147.53",
    prediction: "sell",
    lookup: "garmin",
  },
  {
    ticker: "IT",
    company: "Gartner",
    sector: "Information Technology",
    image: "gartner.svg",
    price: "101.32",
    prediction: "buy",
    lookup: "gartner",
  },
  {
    ticker: "GEHC",
    company: "GE HealthCare",
    sector: "Health Care",
    image: "ge-healthcare-technologies.svg",
    price: "86.49",
    prediction: "buy",
    lookup: "ge-healthcare",
  },
  {
    ticker: "GEN",
    company: "Gen Digital",
    sector: "Information Technology",
    image: "gen-digital.svg",
    price: "163.20",
    prediction: "sell",
    lookup: "gen-digital",
  },
  {
    ticker: "GNRC",
    company: "Generac",
    sector: "Industrials",
    image: "generac-power-systems.svg",
    price: "158.43",
    prediction: "sell",
    lookup: "generac",
  },
  {
    ticker: "GD",
    company: "General Dynamics",
    sector: "Industrials",
    image: "general-dynamics.svg",
    price: "123.63",
    prediction: "buy",
    lookup: "general-dynamics",
  },
  {
    ticker: "GE",
    company: "General Electric",
    sector: "Industrials",
    image: "general-electric.svg",
    price: "63.31",
    prediction: "buy",
    lookup: "general-electric",
  },
  {
    ticker: "GIS",
    company: "General Mills",
    sector: "Consumer Staples",
    image: "general-mills.svg",
    price: "173.4",
    prediction: "buy",
    lookup: "general-mills",
  },
  {
    ticker: "GM",
    company: "General Motors",
    sector: "Consumer Discretionary",
    image: "general-motors.svg",
    price: "198.66",
    prediction: "buy",
    lookup: "general-motors",
  },
  {
    ticker: "GPC",
    company: "Genuine Parts Company",
    sector: "Consumer Discretionary",
    image: "genuine-parts-company.svg",
    price: "128.57",
    prediction: "sell",
    lookup: "genuine-parts-company",
  },
  {
    ticker: "GILD",
    company: "Gilead Sciences",
    sector: "Health Care",
    image: "gilead-sciences.svg",
    price: "172.27",
    prediction: "buy",
    lookup: "gilead-sciences",
  },
  {
    ticker: "GPN",
    company: "Global Payments",
    sector: "Financials",
    image: "global-payments.svg",
    price: "66.23",
    prediction: "sell",
    lookup: "global-payments",
  },
  {
    ticker: "GL",
    company: "Globe Life",
    sector: "Financials",
    image: "globe-life.svg",
    price: "71.95",
    prediction: "sell",
    lookup: "globe-life",
  },
  {
    ticker: "GS",
    company: "Goldman Sachs",
    sector: "Financials",
    image: "goldman-sachs.svg",
    price: "142.62",
    prediction: "buy",
    lookup: "goldman-sachs",
  },
  {
    ticker: "HAL",
    company: "Halliburton",
    sector: "Energy",
    image: "halliburton.svg",
    price: "169.61",
    prediction: "sell",
    lookup: "halliburton",
  },
  {
    ticker: "HIG",
    company: "Hartford (The)",
    sector: "Financials",
    image: "default.svg",
    price: "97.17",
    prediction: "buy",
    lookup: "hartford-(the)",
  },
  {
    ticker: "HAS",
    company: "Hasbro",
    sector: "Consumer Discretionary",
    image: "hasbro.svg",
    price: "165.33",
    prediction: "buy",
    lookup: "hasbro",
  },
  {
    ticker: "HCA",
    company: "HCA Healthcare",
    sector: "Health Care",
    image: "hca-healthcare.svg",
    price: "45.13",
    prediction: "sell",
    lookup: "hca-healthcare",
  },
  {
    ticker: "PEAK",
    company: "Healthpeak",
    sector: "Real Estate",
    image: "default.svg",
    price: "135.34",
    prediction: "sell",
    lookup: "healthpeak",
  },
  {
    ticker: "HSIC",
    company: "Henry Schein",
    sector: "Health Care",
    image: "henry-schein.svg",
    price: "186.53",
    prediction: "buy",
    lookup: "henry-schein",
  },
  {
    ticker: "HSY",
    company: "Hershey's",
    sector: "Consumer Staples",
    image: "hershey-company.svg",
    price: "160.43",
    prediction: "sell",
    lookup: "hershey's",
  },
  {
    ticker: "HES",
    company: "Hess Corporation",
    sector: "Energy",
    image: "hess.svg",
    price: "195.54",
    prediction: "sell",
    lookup: "hess-corporation",
  },
  {
    ticker: "HPE",
    company: "Hewlett Packard Enterprise",
    sector: "Information Technology",
    image: "hewlett-packard-enterprise.svg",
    price: "181.22",
    prediction: "buy",
    lookup: "hewlett-packard-enterprise",
  },
  {
    ticker: "HLT",
    company: "Hilton Worldwide",
    sector: "Consumer Discretionary",
    image: "hilton-hotels.svg",
    price: "99.27",
    prediction: "sell",
    lookup: "hilton-worldwide",
  },
  {
    ticker: "HOLX",
    company: "Hologic",
    sector: "Health Care",
    image: "hologic.svg",
    price: "116.73",
    prediction: "sell",
    lookup: "hologic",
  },
  {
    ticker: "HD",
    company: "Home Depot (The)",
    sector: "Consumer Discretionary",
    image: "home-depot.svg",
    price: "198.40",
    prediction: "sell",
    lookup: "home-depot-(the)",
  },
  {
    ticker: "HON",
    company: "Honeywell",
    sector: "Industrials",
    image: "honeywell.svg",
    price: "149.98",
    prediction: "buy",
    lookup: "honeywell",
  },
  {
    ticker: "HRL",
    company: "Hormel Foods",
    sector: "Consumer Staples",
    image: "hormel-foods.svg",
    price: "134.74",
    prediction: "buy",
    lookup: "hormel-foods",
  },
  {
    ticker: "HST",
    company: "Host Hotels & Resorts",
    sector: "Real Estate",
    image: "host-hotels-and-resorts.svg",
    price: "139.35",
    prediction: "buy",
    lookup: "host-hotels-&-resorts",
  },
  {
    ticker: "HWM",
    company: "Howmet Aerospace",
    sector: "Industrials",
    image: "howmet-aerospace.svg",
    price: "162.70",
    prediction: "sell",
    lookup: "howmet-aerospace",
  },
  {
    ticker: "HPQ",
    company: "HP Inc.",
    sector: "Information Technology",
    image: "hp.svg",
    price: "44.86",
    prediction: "buy",
    lookup: "hp-inc.",
  },
  {
    ticker: "HUBB",
    company: "Hubbell Incorporated",
    sector: "Industrials",
    image: "hubbell.svg",
    price: "143.49",
    prediction: "buy",
    lookup: "hubbell-incorporated",
  },
  {
    ticker: "HUM",
    company: "Humana",
    sector: "Health Care",
    image: "humana.svg",
    price: "151.86",
    prediction: "sell",
    lookup: "humana",
  },
  {
    ticker: "HBAN",
    company: "Huntington Bancshares",
    sector: "Financials",
    image: "huntington-bancshares.svg",
    price: "45.63",
    prediction: "buy",
    lookup: "huntington-bancshares",
  },
  {
    ticker: "HII",
    company: "Huntington Ingalls Industries",
    sector: "Industrials",
    image: "huntington-ingalls-industries.svg",
    price: "195.50",
    prediction: "sell",
    lookup: "huntington-ingalls-industries",
  },
  {
    ticker: "IBM",
    company: "IBM",
    sector: "Information Technology",
    image: "ibm.svg",
    price: "164.8",
    prediction: "buy",
    lookup: "ibm",
  },
  {
    ticker: "IEX",
    company: "IDEX Corporation",
    sector: "Industrials",
    image: "idex.svg",
    price: "131.3",
    prediction: "sell",
    lookup: "idex-corporation",
  },
  {
    ticker: "IDXX",
    company: "Idexx Laboratories",
    sector: "Health Care",
    image: "idexx-laboratories.svg",
    price: "73.84",
    prediction: "sell",
    lookup: "idexx-laboratories",
  },
  {
    ticker: "ITW",
    company: "Illinois Tool Works",
    sector: "Industrials",
    image: "illinois-tool-works.svg",
    price: "155.52",
    prediction: "sell",
    lookup: "illinois-tool-works",
  },
  {
    ticker: "ILMN",
    company: "Illumina",
    sector: "Health Care",
    image: "illumina.svg",
    price: "54.88",
    prediction: "buy",
    lookup: "illumina",
  },
  {
    ticker: "INCY",
    company: "Incyte",
    sector: "Health Care",
    image: "incyte.svg",
    price: "102.6",
    prediction: "sell",
    lookup: "incyte",
  },
  {
    ticker: "IR",
    company: "Ingersoll Rand",
    sector: "Industrials",
    image: "ingersoll-rand.svg",
    price: "175.17",
    prediction: "sell",
    lookup: "ingersoll-rand",
  },
  {
    ticker: "PODD",
    company: "Insulet",
    sector: "Health Care",
    image: "insulet.svg",
    price: "172.87",
    prediction: "buy",
    lookup: "insulet",
  },
  {
    ticker: "INTC",
    company: "Intel",
    sector: "Information Technology",
    image: "intel.svg",
    price: "52.5",
    prediction: "buy",
    lookup: "intel",
  },
  {
    ticker: "ICE",
    company: "Intercontinental Exchange",
    sector: "Financials",
    image: "intercontinental-exchange.svg",
    price: "136.39",
    prediction: "buy",
    lookup: "intercontinental-exchange",
  },
  {
    ticker: "IFF",
    company: "International Flavors & Fragrances",
    sector: "Materials",
    image: "iff.svg",
    price: "133.82",
    prediction: "buy",
    lookup: "international-flavors-&-fragrances",
  },
  {
    ticker: "IP",
    company: "International Paper",
    sector: "Materials",
    image: "international-paper.svg",
    price: "175.46",
    prediction: "buy",
    lookup: "international-paper",
  },
  {
    ticker: "IPG",
    company: "Interpublic Group of Companies (The)",
    sector: "Communication Services",
    image: "ipg.svg",
    price: "190.66",
    prediction: "buy",
    lookup: "interpublic-group-of-companies-(the)",
  },
  {
    ticker: "INTU",
    company: "Intuit",
    sector: "Information Technology",
    image: "intuit.svg",
    price: "42.73",
    prediction: "buy",
    lookup: "intuit",
  },
  {
    ticker: "ISRG",
    company: "Intuitive Surgical",
    sector: "Health Care",
    image: "intuitive-surgical.svg",
    price: "119.14",
    prediction: "buy",
    lookup: "intuitive-surgical",
  },
  {
    ticker: "IVZ",
    company: "Invesco",
    sector: "Financials",
    image: "invesco.svg",
    price: "175.68",
    prediction: "sell",
    lookup: "invesco",
  },
  {
    ticker: "INVH",
    company: "Invitation Homes",
    sector: "Real Estate",
    image: "invitation-homes.svg",
    price: "52.59",
    prediction: "sell",
    lookup: "invitation-homes",
  },
  {
    ticker: "IQV",
    company: "IQVIA",
    sector: "Health Care",
    image: "iqvia.svg",
    price: "30.92",
    prediction: "buy",
    lookup: "iqvia",
  },
  {
    ticker: "IRM",
    company: "Iron Mountain",
    sector: "Real Estate",
    image: "iron-mountain.svg",
    price: "169.61",
    prediction: "sell",
    lookup: "iron-mountain",
  },
  {
    ticker: "JBHT",
    company: "J.B. Hunt",
    sector: "Industrials",
    image: "jb-hunt.svg",
    price: "78.49",
    prediction: "sell",
    lookup: "j.b.-hunt",
  },
  {
    ticker: "JKHY",
    company: "Jack Henry & Associates",
    sector: "Financials",
    image: "jack-henry-amd-associates.svg",
    price: "98.21",
    prediction: "buy",
    lookup: "jack-henry-&-associates",
  },
  {
    ticker: "J",
    company: "Jacobs Solutions",
    sector: "Industrials",
    image: "jacobs-engineering.svg",
    price: "40.84",
    prediction: "sell",
    lookup: "jacobs-solutions",
  },
  {
    ticker: "JNJ",
    company: "Johnson & Johnson",
    sector: "Health Care",
    image: "johnson-and-johnson.svg",
    price: "179.53",
    prediction: "sell",
    lookup: "johnson-&-johnson",
  },
  {
    ticker: "JCI",
    company: "Johnson Controls",
    sector: "Industrials",
    image: "johnson-controls.svg",
    price: "103.83",
    prediction: "sell",
    lookup: "johnson-controls",
  },
  {
    ticker: "JPM",
    company: "JPMorgan Chase",
    sector: "Financials",
    image: "jp-morgan-chase.svg",
    price: "137.61",
    prediction: "sell",
    lookup: "jpmorgan-chase",
  },
  {
    ticker: "JNPR",
    company: "Juniper Networks",
    sector: "Information Technology",
    image: "juniper-networks.svg",
    price: "186.74",
    prediction: "sell",
    lookup: "juniper-networks",
  },
  {
    ticker: "K",
    company: "Kellanova",
    sector: "Consumer Staples",
    image: "kellogg-company.svg",
    price: "84.51",
    prediction: "sell",
    lookup: "kellanova",
  },
  {
    ticker: "KVUE",
    company: "Kenvue",
    sector: "Consumer Staples",
    image: "kenvue.svg",
    price: "168.90",
    prediction: "sell",
    lookup: "kenvue",
  },
  {
    ticker: "KDP",
    company: "Keurig Dr Pepper",
    sector: "Consumer Staples",
    image: "keurig-dr-pepper.svg",
    price: "88.71",
    prediction: "sell",
    lookup: "keurig-dr-pepper",
  },
  {
    ticker: "KEY",
    company: "KeyCorp",
    sector: "Financials",
    image: "keycorp.svg",
    price: "108.58",
    prediction: "sell",
    lookup: "keycorp",
  },
  {
    ticker: "KEYS",
    company: "Keysight",
    sector: "Information Technology",
    image: "keysight.svg",
    price: "169.99",
    prediction: "sell",
    lookup: "keysight",
  },
  {
    ticker: "KMB",
    company: "Kimberly-Clark",
    sector: "Consumer Staples",
    image: "kimberly-clark.svg",
    price: "74.7",
    prediction: "sell",
    lookup: "kimberly-clark",
  },
  {
    ticker: "KIM",
    company: "Kimco Realty",
    sector: "Real Estate",
    image: "kimco-realty.svg",
    price: "148.52",
    prediction: "sell",
    lookup: "kimco-realty",
  },
  {
    ticker: "KMI",
    company: "Kinder Morgan",
    sector: "Energy",
    image: "kinder-morgan.svg",
    price: "147.50",
    prediction: "buy",
    lookup: "kinder-morgan",
  },
  {
    ticker: "KLAC",
    company: "KLA Corporation",
    sector: "Information Technology",
    image: "kla.svg",
    price: "46.38",
    prediction: "buy",
    lookup: "kla-corporation",
  },
  {
    ticker: "KHC",
    company: "Kraft Heinz",
    sector: "Consumer Staples",
    image: "kraft-heinz.svg",
    price: "163.37",
    prediction: "sell",
    lookup: "kraft-heinz",
  },
  {
    ticker: "KR",
    company: "Kroger",
    sector: "Consumer Staples",
    image: "kroger.svg",
    price: "99.70",
    prediction: "sell",
    lookup: "kroger",
  },
  {
    ticker: "LHX",
    company: "L3Harris",
    sector: "Industrials",
    image: "l3harris-technologies.svg",
    price: "102.62",
    prediction: "buy",
    lookup: "l3harris",
  },
  {
    ticker: "LH",
    company: "LabCorp",
    sector: "Health Care",
    image: "labcorp.svg",
    price: "70.87",
    prediction: "sell",
    lookup: "labcorp",
  },
  {
    ticker: "LRCX",
    company: "Lam Research",
    sector: "Information Technology",
    image: "lam-research.svg",
    price: "54.98",
    prediction: "buy",
    lookup: "lam-research",
  },
  {
    ticker: "LW",
    company: "Lamb Weston",
    sector: "Consumer Staples",
    image: "lamb-weston.svg",
    price: "67.82",
    prediction: "buy",
    lookup: "lamb-weston",
  },
  {
    ticker: "LVS",
    company: "Las Vegas Sands",
    sector: "Consumer Discretionary",
    image: "las-vegas-sands.svg",
    price: "158.80",
    prediction: "sell",
    lookup: "las-vegas-sands",
  },
  {
    ticker: "LDOS",
    company: "Leidos",
    sector: "Industrials",
    image: "leidos.svg",
    price: "76.14",
    prediction: "buy",
    lookup: "leidos",
  },
  {
    ticker: "LEN",
    company: "Lennar",
    sector: "Consumer Discretionary",
    image: "lennar.svg",
    price: "200.74",
    prediction: "buy",
    lookup: "lennar",
  },
  {
    ticker: "LIN",
    company: "Linde plc",
    sector: "Materials",
    image: "linde.svg",
    price: "67.89",
    prediction: "buy",
    lookup: "linde-plc",
  },
  {
    ticker: "LYV",
    company: "Live Nation Entertainment",
    sector: "Communication Services",
    image: "live-nation.svg",
    price: "137.18",
    prediction: "buy",
    lookup: "live-nation-entertainment",
  },
  {
    ticker: "LKQ",
    company: "LKQ Corporation",
    sector: "Consumer Discretionary",
    image: "lkq-corporation.svg",
    price: "169.46",
    prediction: "sell",
    lookup: "lkq-corporation",
  },
  {
    ticker: "LMT",
    company: "Lockheed Martin",
    sector: "Industrials",
    image: "lockheed-martin.svg",
    price: "156.91",
    prediction: "sell",
    lookup: "lockheed-martin",
  },
  {
    ticker: "L",
    company: "Loews Corporation",
    sector: "Financials",
    image: "loews-corporation.svg",
    price: "170.53",
    prediction: "sell",
    lookup: "loews-corporation",
  },
  {
    ticker: "LOW",
    company: "Lowe's",
    sector: "Consumer Discretionary",
    image: "default.svg",
    price: "51.45",
    prediction: "buy",
    lookup: "lowe's",
  },
  {
    ticker: "LULU",
    company: "Lululemon Athletica",
    sector: "Consumer Discretionary",
    image: "lululemon-athletica.svg",
    price: "139.14",
    prediction: "sell",
    lookup: "lululemon-athletica",
  },
  {
    ticker: "LYB",
    company: "LyondellBasell",
    sector: "Materials",
    image: "lyondellbasell.svg",
    price: "104.93",
    prediction: "buy",
    lookup: "lyondellbasell",
  },
  {
    ticker: "MTB",
    company: "M&T Bank",
    sector: "Financials",
    image: "default.svg",
    price: "54.40",
    prediction: "sell",
    lookup: "m&t-bank",
  },
  {
    ticker: "MRO",
    company: "Marathon Oil",
    sector: "Energy",
    image: "marathon-oil.svg",
    price: "43.82",
    prediction: "sell",
    lookup: "marathon-oil",
  },
  {
    ticker: "MPC",
    company: "Marathon Petroleum",
    sector: "Energy",
    image: "marathon-petroleum.svg",
    price: "170.71",
    prediction: "sell",
    lookup: "marathon-petroleum",
  },
  {
    ticker: "MKTX",
    company: "MarketAxess",
    sector: "Financials",
    image: "default.svg",
    price: "127.20",
    prediction: "sell",
    lookup: "marketaxess",
  },
  {
    ticker: "MAR",
    company: "Marriott International",
    sector: "Consumer Discretionary",
    image: "marriott-international.svg",
    price: "199.10",
    prediction: "sell",
    lookup: "marriott-international",
  },
  {
    ticker: "MMC",
    company: "Marsh McLennan",
    sector: "Financials",
    image: "default.svg",
    price: "108.92",
    prediction: "sell",
    lookup: "marsh-mclennan",
  },
  {
    ticker: "MLM",
    company: "Martin Marietta Materials",
    sector: "Materials",
    image: "martin-marietta.svg",
    price: "82.93",
    prediction: "buy",
    lookup: "martin-marietta-materials",
  },
  {
    ticker: "MAS",
    company: "Masco",
    sector: "Industrials",
    image: "masco.svg",
    price: "173.68",
    prediction: "sell",
    lookup: "masco",
  },
  {
    ticker: "MA",
    company: "Mastercard",
    sector: "Financials",
    image: "mastercard.svg",
    price: "130.62",
    prediction: "buy",
    lookup: "mastercard",
  },
  {
    ticker: "MTCH",
    company: "Match Group",
    sector: "Communication Services",
    image: "match-group.svg",
    price: "128.15",
    prediction: "sell",
    lookup: "match-group",
  },
  {
    ticker: "MKC",
    company: "McCormick & Company",
    sector: "Consumer Staples",
    image: "mc-cormick.svg",
    price: "146.10",
    prediction: "buy",
    lookup: "mccormick-&-company",
  },
  {
    ticker: "MCD",
    company: "McDonald's",
    sector: "Consumer Discretionary",
    image: "mcdonald.svg",
    price: "112.35",
    prediction: "buy",
    lookup: "mcdonald's",
  },
  {
    ticker: "MCK",
    company: "McKesson",
    sector: "Health Care",
    image: "mckesson.svg",
    price: "121.58",
    prediction: "sell",
    lookup: "mckesson",
  },
  {
    ticker: "MDT",
    company: "Medtronic",
    sector: "Health Care",
    image: "medtronic.svg",
    price: "192.65",
    prediction: "buy",
    lookup: "medtronic",
  },
  {
    ticker: "MRK",
    company: "Merck & Co.",
    sector: "Health Care",
    image: "merck.svg",
    price: "98.72",
    prediction: "buy",
    lookup: "merck-&-co.",
  },
  {
    ticker: "META",
    company: "Meta Platforms",
    sector: "Communication Services",
    image: "meta-platforms.svg",
    price: "142.15",
    prediction: "sell",
    lookup: "meta-platforms",
  },
  {
    ticker: "MET",
    company: "MetLife",
    sector: "Financials",
    image: "metlife.svg",
    price: "152.57",
    prediction: "sell",
    lookup: "metlife",
  },
  {
    ticker: "MTD",
    company: "Mettler Toledo",
    sector: "Health Care",
    image: "default.svg",
    price: "109.78",
    prediction: "buy",
    lookup: "mettler-toledo",
  },
  {
    ticker: "MGM",
    company: "MGM Resorts",
    sector: "Consumer Discretionary",
    image: "mgm-resorts.svg",
    price: "190.99",
    prediction: "sell",
    lookup: "mgm-resorts",
  },
  {
    ticker: "MCHP",
    company: "Microchip Technology",
    sector: "Information Technology",
    image: "microchip-technology.svg",
    price: "139.66",
    prediction: "sell",
    lookup: "microchip-technology",
  },
  {
    ticker: "MU",
    company: "Micron Technology",
    sector: "Information Technology",
    image: "micron-technology.svg",
    price: "198.35",
    prediction: "sell",
    lookup: "micron-technology",
  },
  {
    ticker: "MSFT",
    company: "Microsoft",
    sector: "Information Technology",
    image: "microsoft.svg",
    price: "88.1",
    prediction: "buy",
    lookup: "microsoft",
  },
  {
    ticker: "MAA",
    company: "Mid-America Apartment Communities",
    sector: "Real Estate",
    image: "mid-america-apartment-communities.svg",
    price: "105.69",
    prediction: "sell",
    lookup: "mid-america-apartment-communities",
  },
  {
    ticker: "MRNA",
    company: "Moderna",
    sector: "Health Care",
    image: "moderna.svg",
    price: "45.44",
    prediction: "buy",
    lookup: "moderna",
  },
  {
    ticker: "MHK",
    company: "Mohawk Industries",
    sector: "Consumer Discretionary",
    image: "mohawk-industries.svg",
    price: "81.97",
    prediction: "buy",
    lookup: "mohawk-industries",
  },
  {
    ticker: "MOH",
    company: "Molina Healthcare",
    sector: "Health Care",
    image: "molina-healthcare.svg",
    price: "32.36",
    prediction: "sell",
    lookup: "molina-healthcare",
  },
  {
    ticker: "TAP",
    company: "Molson Coors Beverage Company",
    sector: "Consumer Staples",
    image: "molson-coors.svg",
    price: "188.77",
    prediction: "sell",
    lookup: "molson-coors-beverage-company",
  },
  {
    ticker: "MDLZ",
    company: "Mondelez International",
    sector: "Consumer Staples",
    image: "mondelez.svg",
    price: "192.76",
    prediction: "sell",
    lookup: "mondelez-international",
  },
  {
    ticker: "MPWR",
    company: "Monolithic Power Systems",
    sector: "Information Technology",
    image: "monolithic-power-systems.svg",
    price: "169.65",
    prediction: "sell",
    lookup: "monolithic-power-systems",
  },
  {
    ticker: "MNST",
    company: "Monster Beverage",
    sector: "Consumer Staples",
    image: "monster-beverage.svg",
    price: "116.79",
    prediction: "buy",
    lookup: "monster-beverage",
  },
  {
    ticker: "MCO",
    company: "Moody's Corporation",
    sector: "Financials",
    image: "default.svg",
    price: "157.40",
    prediction: "buy",
    lookup: "moody's-corporation",
  },
  {
    ticker: "MS",
    company: "Morgan Stanley",
    sector: "Financials",
    image: "morgan-stanley.svg",
    price: "111.91",
    prediction: "sell",
    lookup: "morgan-stanley",
  },
  {
    ticker: "MOS",
    company: "Mosaic Company (The)",
    sector: "Materials",
    image: "the-mosaic-company.svg",
    price: "197.11",
    prediction: "buy",
    lookup: "mosaic-company-(the)",
  },
  {
    ticker: "MSI",
    company: "Motorola Solutions",
    sector: "Information Technology",
    image: "motorola-solutions.svg",
    price: "198.42",
    prediction: "buy",
    lookup: "motorola-solutions",
  },
  {
    ticker: "MSCI",
    company: "MSCI",
    sector: "Financials",
    image: "msci.svg",
    price: "69.18",
    prediction: "sell",
    lookup: "msci",
  },
  {
    ticker: "NDAQ",
    company: "Nasdaq, Inc.",
    sector: "Financials",
    image: "nasdaq.svg",
    price: "117.72",
    prediction: "sell",
    lookup: "nasdaq,-inc.",
  },
  {
    ticker: "NTAP",
    company: "NetApp",
    sector: "Information Technology",
    image: "netapp.svg",
    price: "178.51",
    prediction: "sell",
    lookup: "netapp",
  },
  {
    ticker: "NFLX",
    company: "Netflix",
    sector: "Communication Services",
    image: "netflix.svg",
    price: "103.61",
    prediction: "buy",
    lookup: "netflix",
  },
  {
    ticker: "NEM",
    company: "Newmont",
    sector: "Materials",
    image: "newmont.svg",
    price: "165.48",
    prediction: "sell",
    lookup: "newmont",
  },
  {
    ticker: "NWSA",
    company: "News Corp (Class A)",
    sector: "Communication Services",
    image: "default.svg",
    price: "188.26",
    prediction: "sell",
    lookup: "news-corp-(class-a)",
  },
  {
    ticker: "NWS",
    company: "News Corp (Class B)",
    sector: "Communication Services",
    image: "news-corp.svg",
    price: "172.48",
    prediction: "sell",
    lookup: "news-corp-(class-b)",
  },
  {
    ticker: "NEE",
    company: "NextEra Energy",
    sector: "Utilities",
    image: "nextera-energy.svg",
    price: "100.49",
    prediction: "buy",
    lookup: "nextera-energy",
  },
  {
    ticker: "NKE",
    company: "Nike, Inc.",
    sector: "Consumer Discretionary",
    image: "nike.svg",
    price: "74.55",
    prediction: "buy",
    lookup: "nike,-inc.",
  },
  {
    ticker: "NI",
    company: "NiSource",
    sector: "Utilities",
    image: "nisource.svg",
    price: "53.75",
    prediction: "buy",
    lookup: "nisource",
  },
  {
    ticker: "NDSN",
    company: "Nordson Corporation",
    sector: "Industrials",
    image: "nordson.svg",
    price: "190.49",
    prediction: "buy",
    lookup: "nordson-corporation",
  },
  {
    ticker: "NSC",
    company: "Norfolk Southern Railway",
    sector: "Industrials",
    image: "norfolk-southern.svg",
    price: "159.10",
    prediction: "sell",
    lookup: "norfolk-southern-railway",
  },
  {
    ticker: "NTRS",
    company: "Northern Trust",
    sector: "Financials",
    image: "northern-trust.svg",
    price: "69.40",
    prediction: "buy",
    lookup: "northern-trust",
  },
  {
    ticker: "NOC",
    company: "Northrop Grumman",
    sector: "Industrials",
    image: "northrop-grumman.svg",
    price: "158.96",
    prediction: "sell",
    lookup: "northrop-grumman",
  },
  {
    ticker: "NCLH",
    company: "Norwegian Cruise Line Holdings",
    sector: "Consumer Discretionary",
    image: "norwegian-cruise-line.svg",
    price: "199.8",
    prediction: "buy",
    lookup: "norwegian-cruise-line-holdings",
  },
  {
    ticker: "NRG",
    company: "NRG Energy",
    sector: "Utilities",
    image: "default.svg",
    price: "33.18",
    prediction: "sell",
    lookup: "nrg-energy",
  },
  {
    ticker: "NUE",
    company: "Nucor",
    sector: "Materials",
    image: "nucor.svg",
    price: "114.61",
    prediction: "sell",
    lookup: "nucor",
  },
  {
    ticker: "NVDA",
    company: "Nvidia",
    sector: "Information Technology",
    image: "nvidia.svg",
    price: "139.12",
    prediction: "buy",
    lookup: "nvidia",
  },
  {
    ticker: "NVR",
    company: "NVR, Inc.",
    sector: "Consumer Discretionary",
    image: "nvr.svg",
    price: "181.78",
    prediction: "buy",
    lookup: "nvr,-inc.",
  },
  {
    ticker: "NXPI",
    company: "NXP Semiconductors",
    sector: "Information Technology",
    image: "nxp-semiconductors.svg",
    price: "158.12",
    prediction: "sell",
    lookup: "nxp-semiconductors",
  },
  {
    ticker: "ORLY",
    company: "O'Reilly Auto Parts",
    sector: "Consumer Discretionary",
    image: "o-reilly-automotive.svg",
    price: "103.21",
    prediction: "buy",
    lookup: "o'reilly-auto-parts",
  },
  {
    ticker: "OXY",
    company: "Occidental Petroleum",
    sector: "Energy",
    image: "occidental-petroleum.svg",
    price: "140.95",
    prediction: "sell",
    lookup: "occidental-petroleum",
  },
  {
    ticker: "ODFL",
    company: "Old Dominion",
    sector: "Industrials",
    image: "old-dominion-freight-line.png",
    price: "60.14",
    prediction: "buy",
    lookup: "old-dominion",
  },
  {
    ticker: "OMC",
    company: "Omnicom Group",
    sector: "Communication Services",
    image: "omnicom.svg",
    price: "143.60",
    prediction: "buy",
    lookup: "omnicom-group",
  },
  {
    ticker: "ON",
    company: "ON Semiconductor",
    sector: "Information Technology",
    image: "on-semiconductor.svg",
    price: "168.73",
    prediction: "sell",
    lookup: "on-semiconductor",
  },
  {
    ticker: "OKE",
    company: "ONEOK",
    sector: "Energy",
    image: "oneok.svg",
    price: "132.19",
    prediction: "buy",
    lookup: "oneok",
  },
  {
    ticker: "ORCL",
    company: "Oracle Corporation",
    sector: "Information Technology",
    image: "oracle.svg",
    price: "172.5",
    prediction: "sell",
    lookup: "oracle-corporation",
  },
  {
    ticker: "OTIS",
    company: "Otis Worldwide",
    sector: "Industrials",
    image: "otis-worldwide.svg",
    price: "35.36",
    prediction: "buy",
    lookup: "otis-worldwide",
  },
  {
    ticker: "PCAR",
    company: "Paccar",
    sector: "Industrials",
    image: "paccar.svg",
    price: "44.42",
    prediction: "buy",
    lookup: "paccar",
  },
  {
    ticker: "PKG",
    company: "Packaging Corporation of America",
    sector: "Materials",
    image: "packaging-corporation-of-america.svg",
    price: "148.61",
    prediction: "buy",
    lookup: "packaging-corporation-of-america",
  },
  {
    ticker: "PANW",
    company: "Palo Alto Networks",
    sector: "Information Technology",
    image: "palo-alto-networks.svg",
    price: "59.20",
    prediction: "sell",
    lookup: "palo-alto-networks",
  },
  {
    ticker: "PARA",
    company: "Paramount Global",
    sector: "Communication Services",
    image: "paramount.svg",
    price: "67.46",
    prediction: "sell",
    lookup: "paramount-global",
  },
  {
    ticker: "PH",
    company: "Parker Hannifin",
    sector: "Industrials",
    image: "parker-hannifin.svg",
    price: "154.50",
    prediction: "buy",
    lookup: "parker-hannifin",
  },
  {
    ticker: "PAYX",
    company: "Paychex",
    sector: "Industrials",
    image: "paychex.svg",
    price: "39.87",
    prediction: "buy",
    lookup: "paychex",
  },
  {
    ticker: "PAYC",
    company: "Paycom",
    sector: "Industrials",
    image: "paycom.svg",
    price: "199.77",
    prediction: "sell",
    lookup: "paycom",
  },
  {
    ticker: "PYPL",
    company: "PayPal",
    sector: "Financials",
    image: "paypal.svg",
    price: "125.41",
    prediction: "sell",
    lookup: "paypal",
  },
  {
    ticker: "PNR",
    company: "Pentair",
    sector: "Industrials",
    image: "pentair.svg",
    price: "195.97",
    prediction: "sell",
    lookup: "pentair",
  },
  {
    ticker: "PEP",
    company: "PepsiCo",
    sector: "Consumer Staples",
    image: "pepsico.svg",
    price: "93.49",
    prediction: "buy",
    lookup: "pepsico",
  },
  {
    ticker: "PFE",
    company: "Pfizer",
    sector: "Health Care",
    image: "pfizer.svg",
    price: "123.56",
    prediction: "buy",
    lookup: "pfizer",
  },
  {
    ticker: "PCG",
    company: "PG&E Corporation",
    sector: "Utilities",
    image: "pacific-gas-and-electric.svg",
    price: "95.80",
    prediction: "buy",
    lookup: "pg&e-corporation",
  },
  {
    ticker: "PM",
    company: "Philip Morris International",
    sector: "Consumer Staples",
    image: "philip-morris.svg",
    price: "169.76",
    prediction: "sell",
    lookup: "philip-morris-international",
  },
  {
    ticker: "PSX",
    company: "Phillips 66",
    sector: "Energy",
    image: "phillips-66.svg",
    price: "112.36",
    prediction: "sell",
    lookup: "phillips-66",
  },
  {
    ticker: "PNW",
    company: "Pinnacle West",
    sector: "Utilities",
    image: "pinnacle-west-capital.svg",
    price: "64.37",
    prediction: "sell",
    lookup: "pinnacle-west",
  },
  {
    ticker: "PXD",
    company: "Pioneer Natural Resources",
    sector: "Energy",
    image: "pioneer-natural-resources.svg",
    price: "179.11",
    prediction: "buy",
    lookup: "pioneer-natural-resources",
  },
  {
    ticker: "PNC",
    company: "PNC Financial Services",
    sector: "Financials",
    image: "pnc-financial-services.svg",
    price: "194.62",
    prediction: "buy",
    lookup: "pnc-financial-services",
  },
  {
    ticker: "POOL",
    company: "Pool Corporation",
    sector: "Consumer Discretionary",
    image: "poolcorp.svg",
    price: "124.86",
    prediction: "sell",
    lookup: "pool-corporation",
  },
  {
    ticker: "PPG",
    company: "PPG Industries",
    sector: "Materials",
    image: "ppg-industries.svg",
    price: "85.84",
    prediction: "buy",
    lookup: "ppg-industries",
  },
  {
    ticker: "PPL",
    company: "PPL Corporation",
    sector: "Utilities",
    image: "default.svg",
    price: "189.57",
    prediction: "sell",
    lookup: "ppl-corporation",
  },
  {
    ticker: "PFG",
    company: "Principal Financial Group",
    sector: "Financials",
    image: "principal.svg",
    price: "160.69",
    prediction: "sell",
    lookup: "principal-financial-group",
  },
  {
    ticker: "PG",
    company: "Procter & Gamble",
    sector: "Consumer Staples",
    image: "procter-and-gamble.svg",
    price: "128.44",
    prediction: "sell",
    lookup: "procter-&-gamble",
  },
  {
    ticker: "PGR",
    company: "Progressive Corporation",
    sector: "Financials",
    image: "progressive.svg",
    price: "117.8",
    prediction: "sell",
    lookup: "progressive-corporation",
  },
  {
    ticker: "PLD",
    company: "Prologis",
    sector: "Real Estate",
    image: "prologis.svg",
    price: "72.55",
    prediction: "sell",
    lookup: "prologis",
  },
  {
    ticker: "PRU",
    company: "Prudential Financial",
    sector: "Financials",
    image: "prudential-financial.svg",
    price: "151.84",
    prediction: "sell",
    lookup: "prudential-financial",
  },
  {
    ticker: "PEG",
    company: "Public Service Enterprise Group",
    sector: "Utilities",
    image: "default.svg",
    price: "162.24",
    prediction: "sell",
    lookup: "public-service-enterprise-group",
  },
  {
    ticker: "PTC",
    company: "PTC",
    sector: "Information Technology",
    image: "ptc.svg",
    price: "86.17",
    prediction: "buy",
    lookup: "ptc",
  },
  {
    ticker: "PSA",
    company: "Public Storage",
    sector: "Real Estate",
    image: "public-storage.svg",
    price: "50.69",
    prediction: "sell",
    lookup: "public-storage",
  },
  {
    ticker: "PHM",
    company: "PulteGroup",
    sector: "Consumer Discretionary",
    image: "pultegroup.svg",
    price: "85.18",
    prediction: "buy",
    lookup: "pultegroup",
  },
  {
    ticker: "QRVO",
    company: "Qorvo",
    sector: "Information Technology",
    image: "qorvo.svg",
    price: "137.8",
    prediction: "buy",
    lookup: "qorvo",
  },
  {
    ticker: "PWR",
    company: "Quanta Services",
    sector: "Industrials",
    image: "default.svg",
    price: "50.1",
    prediction: "buy",
    lookup: "quanta-services",
  },
  {
    ticker: "QCOM",
    company: "Qualcomm",
    sector: "Information Technology",
    image: "qualcomm.svg",
    price: "38.46",
    prediction: "buy",
    lookup: "qualcomm",
  },
  {
    ticker: "DGX",
    company: "Quest Diagnostics",
    sector: "Health Care",
    image: "quest-diagnostics.svg",
    price: "107.23",
    prediction: "sell",
    lookup: "quest-diagnostics",
  },
  {
    ticker: "RL",
    company: "Ralph Lauren Corporation",
    sector: "Consumer Discretionary",
    image: "ralph-lauren.svg",
    price: "189.90",
    prediction: "sell",
    lookup: "ralph-lauren-corporation",
  },
  {
    ticker: "RJF",
    company: "Raymond James",
    sector: "Financials",
    image: "raymond-james.svg",
    price: "187.83",
    prediction: "buy",
    lookup: "raymond-james",
  },
  {
    ticker: "RTX",
    company: "RTX Corporation",
    sector: "Industrials",
    image: "default.svg",
    price: "131.89",
    prediction: "buy",
    lookup: "rtx-corporation",
  },
  {
    ticker: "O",
    company: "Realty Income",
    sector: "Real Estate",
    image: "default.svg",
    price: "108.97",
    prediction: "sell",
    lookup: "realty-income",
  },
  {
    ticker: "REG",
    company: "Regency Centers",
    sector: "Real Estate",
    image: "regency-centers.svg",
    price: "59.21",
    prediction: "sell",
    lookup: "regency-centers",
  },
  {
    ticker: "REGN",
    company: "Regeneron",
    sector: "Health Care",
    image: "regeneron-pharmaceuticals.svg",
    price: "163.1",
    prediction: "buy",
    lookup: "regeneron",
  },
  {
    ticker: "RF",
    company: "Regions Financial Corporation",
    sector: "Financials",
    image: "regions-financial.svg",
    price: "194.2",
    prediction: "buy",
    lookup: "regions-financial-corporation",
  },
  {
    ticker: "RSG",
    company: "Republic Services",
    sector: "Industrials",
    image: "republic-services.svg",
    price: "137.51",
    prediction: "sell",
    lookup: "republic-services",
  },
  {
    ticker: "RMD",
    company: "ResMed",
    sector: "Health Care",
    image: "resmed.svg",
    price: "77.91",
    prediction: "buy",
    lookup: "resmed",
  },
  {
    ticker: "RVTY",
    company: "Revvity",
    sector: "Health Care",
    image: "revvity.svg",
    price: "34.56",
    prediction: "buy",
    lookup: "revvity",
  },
  {
    ticker: "RHI",
    company: "Robert Half",
    sector: "Industrials",
    image: "robert-half.svg",
    price: "83.40",
    prediction: "buy",
    lookup: "robert-half",
  },
  {
    ticker: "ROK",
    company: "Rockwell Automation",
    sector: "Industrials",
    image: "default.svg",
    price: "112.40",
    prediction: "sell",
    lookup: "rockwell-automation",
  },
  {
    ticker: "ROL",
    company: "Rollins, Inc.",
    sector: "Industrials",
    image: "rollins.svg",
    price: "58.38",
    prediction: "buy",
    lookup: "rollins,-inc.",
  },
  {
    ticker: "ROP",
    company: "Roper Technologies",
    sector: "Information Technology",
    image: "roper-technologies.svg",
    price: "58.57",
    prediction: "sell",
    lookup: "roper-technologies",
  },
  {
    ticker: "ROST",
    company: "Ross Stores",
    sector: "Consumer Discretionary",
    image: "ross-stores.svg",
    price: "153.94",
    prediction: "buy",
    lookup: "ross-stores",
  },
  {
    ticker: "RCL",
    company: "Royal Caribbean Group",
    sector: "Consumer Discretionary",
    image: "royal-caribbean.svg",
    price: "152.70",
    prediction: "buy",
    lookup: "royal-caribbean-group",
  },
  {
    ticker: "SPGI",
    company: "S&P Global",
    sector: "Financials",
    image: "default.svg",
    price: "70.38",
    prediction: "buy",
    lookup: "s&p-global",
  },
  {
    ticker: "CRM",
    company: "Salesforce",
    sector: "Information Technology",
    image: "salesforce.svg",
    price: "68.10",
    prediction: "buy",
    lookup: "salesforce",
  },
  {
    ticker: "SBAC",
    company: "SBA Communications",
    sector: "Real Estate",
    image: "default.svg",
    price: "99.60",
    prediction: "sell",
    lookup: "sba-communications",
  },
  {
    ticker: "SLB",
    company: "Schlumberger",
    sector: "Energy",
    image: "schlumberger.svg",
    price: "155.88",
    prediction: "sell",
    lookup: "schlumberger",
  },
  {
    ticker: "STX",
    company: "Seagate Technology",
    sector: "Information Technology",
    image: "seagate.svg",
    price: "182.33",
    prediction: "buy",
    lookup: "seagate-technology",
  },
  {
    ticker: "SEE",
    company: "Sealed Air",
    sector: "Materials",
    image: "sealed-air.svg",
    price: "34.46",
    prediction: "buy",
    lookup: "sealed-air",
  },
  {
    ticker: "SRE",
    company: "Sempra Energy",
    sector: "Utilities",
    image: "sempra-energy.svg",
    price: "133.49",
    prediction: "buy",
    lookup: "sempra-energy",
  },
  {
    ticker: "NOW",
    company: "ServiceNow",
    sector: "Information Technology",
    image: "servicenow.svg",
    price: "175.72",
    prediction: "buy",
    lookup: "servicenow",
  },
  {
    ticker: "SHW",
    company: "Sherwin-Williams",
    sector: "Materials",
    image: "sherwin-williams.svg",
    price: "130.77",
    prediction: "buy",
    lookup: "sherwin-williams",
  },
  {
    ticker: "SPG",
    company: "Simon Property Group",
    sector: "Real Estate",
    image: "simon-property.svg",
    price: "164.86",
    prediction: "buy",
    lookup: "simon-property-group",
  },
  {
    ticker: "SWKS",
    company: "Skyworks Solutions",
    sector: "Information Technology",
    image: "skyworks-solutions.svg",
    price: "83.87",
    prediction: "sell",
    lookup: "skyworks-solutions",
  },
  {
    ticker: "SJM",
    company: "J.M. Smucker Company (The)",
    sector: "Consumer Staples",
    image: "jm-smucker.svg",
    price: "76.59",
    prediction: "buy",
    lookup: "j.m.-smucker-company-(the)",
  },
  {
    ticker: "SNA",
    company: "Snap-on",
    sector: "Industrials",
    image: "snap-on.svg",
    price: "150.72",
    prediction: "sell",
    lookup: "snap-on",
  },
  {
    ticker: "SEDG",
    company: "SolarEdge",
    sector: "Information Technology",
    image: "solaredge.svg",
    price: "167.40",
    prediction: "buy",
    lookup: "solaredge",
  },
  {
    ticker: "SO",
    company: "Southern Company",
    sector: "Utilities",
    image: "southern-company.svg",
    price: "87.95",
    prediction: "buy",
    lookup: "southern-company",
  },
  {
    ticker: "LUV",
    company: "Southwest Airlines",
    sector: "Industrials",
    image: "southwest-airlines.svg",
    price: "59.76",
    prediction: "sell",
    lookup: "southwest-airlines",
  },
  {
    ticker: "SWK",
    company: "Stanley Black & Decker",
    sector: "Industrials",
    image: "stanley-black-and-decker.png",
    price: "127.82",
    prediction: "buy",
    lookup: "stanley-black-&-decker",
  },
  {
    ticker: "SBUX",
    company: "Starbucks",
    sector: "Consumer Discretionary",
    image: "starbucks.svg",
    price: "34.16",
    prediction: "sell",
    lookup: "starbucks",
  },
  {
    ticker: "STT",
    company: "State Street Corporation",
    sector: "Financials",
    image: "state-street-corporation.svg",
    price: "76.10",
    prediction: "sell",
    lookup: "state-street-corporation",
  },
  {
    ticker: "STLD",
    company: "Steel Dynamics",
    sector: "Materials",
    image: "default.svg",
    price: "124.87",
    prediction: "sell",
    lookup: "steel-dynamics",
  },
  {
    ticker: "STE",
    company: "Steris",
    sector: "Health Care",
    image: "steris.svg",
    price: "36.94",
    prediction: "buy",
    lookup: "steris",
  },
  {
    ticker: "SYK",
    company: "Stryker Corporation",
    sector: "Health Care",
    image: "stryker-corporation.svg",
    price: "164.95",
    prediction: "sell",
    lookup: "stryker-corporation",
  },
  {
    ticker: "SYF",
    company: "Synchrony Financial",
    sector: "Financials",
    image: "synchrony.svg",
    price: "75.8",
    prediction: "sell",
    lookup: "synchrony-financial",
  },
  {
    ticker: "SNPS",
    company: "Synopsys",
    sector: "Information Technology",
    image: "synopsys.svg",
    price: "89.58",
    prediction: "sell",
    lookup: "synopsys",
  },
  {
    ticker: "SYY",
    company: "Sysco",
    sector: "Consumer Staples",
    image: "sysco.svg",
    price: "183.91",
    prediction: "sell",
    lookup: "sysco",
  },
  {
    ticker: "TMUS",
    company: "T-Mobile US",
    sector: "Communication Services",
    image: "t-mobile-us.svg",
    price: "112.45",
    prediction: "buy",
    lookup: "t-mobile-us",
  },
  {
    ticker: "TROW",
    company: "T. Rowe Price",
    sector: "Financials",
    image: "t-rowe-price.svg",
    price: "36.65",
    prediction: "sell",
    lookup: "t.-rowe-price",
  },
  {
    ticker: "TTWO",
    company: "Take-Two Interactive",
    sector: "Communication Services",
    image: "take-2-interactive.svg",
    price: "32.56",
    prediction: "buy",
    lookup: "take-two-interactive",
  },
  {
    ticker: "TPR",
    company: "Tapestry, Inc.",
    sector: "Consumer Discretionary",
    image: "tapestry.svg",
    price: "46.24",
    prediction: "sell",
    lookup: "tapestry,-inc.",
  },
  {
    ticker: "TRGP",
    company: "Targa Resources",
    sector: "Energy",
    image: "targa-resources.svg",
    price: "83.90",
    prediction: "sell",
    lookup: "targa-resources",
  },
  {
    ticker: "TGT",
    company: "Target Corporation",
    sector: "Consumer Staples",
    image: "target.svg",
    price: "130.54",
    prediction: "sell",
    lookup: "target-corporation",
  },
  {
    ticker: "TEL",
    company: "TE Connectivity",
    sector: "Information Technology",
    image: "te-connectivity.svg",
    price: "55.29",
    prediction: "sell",
    lookup: "te-connectivity",
  },
  {
    ticker: "TDY",
    company: "Teledyne Technologies",
    sector: "Information Technology",
    image: "teledyne.svg",
    price: "184.78",
    prediction: "sell",
    lookup: "teledyne-technologies",
  },
  {
    ticker: "TFX",
    company: "Teleflex",
    sector: "Health Care",
    image: "teleflex.svg",
    price: "167.92",
    prediction: "sell",
    lookup: "teleflex",
  },
  {
    ticker: "TER",
    company: "Teradyne",
    sector: "Information Technology",
    image: "teradyne.svg",
    price: "159.35",
    prediction: "sell",
    lookup: "teradyne",
  },
  {
    ticker: "TSLA",
    company: "Tesla, Inc.",
    sector: "Consumer Discretionary",
    image: "tesla.svg",
    price: "185.94",
    prediction: "sell",
    lookup: "tesla,-inc.",
  },
  {
    ticker: "TXN",
    company: "Texas Instruments",
    sector: "Information Technology",
    image: "texas-instruments.svg",
    price: "70.52",
    prediction: "buy",
    lookup: "texas-instruments",
  },
  {
    ticker: "TXT",
    company: "Textron",
    sector: "Industrials",
    image: "textron.svg",
    price: "185.60",
    prediction: "sell",
    lookup: "textron",
  },
  {
    ticker: "TMO",
    company: "Thermo Fisher Scientific",
    sector: "Health Care",
    image: "thermo-fisher-scientific.svg",
    price: "188.10",
    prediction: "sell",
    lookup: "thermo-fisher-scientific",
  },
  {
    ticker: "TJX",
    company: "TJX Companies",
    sector: "Consumer Discretionary",
    image: "tjx-companies.svg",
    price: "103.8",
    prediction: "buy",
    lookup: "tjx-companies",
  },
  {
    ticker: "TSCO",
    company: "Tractor Supply",
    sector: "Consumer Discretionary",
    image: "tractor-supply.svg",
    price: "94.98",
    prediction: "sell",
    lookup: "tractor-supply",
  },
  {
    ticker: "TT",
    company: "Trane Technologies",
    sector: "Industrials",
    image: "trane-technologies.svg",
    price: "74.62",
    prediction: "buy",
    lookup: "trane-technologies",
  },
  {
    ticker: "TDG",
    company: "TransDigm Group",
    sector: "Industrials",
    image: "transdigm.svg",
    price: "124.94",
    prediction: "sell",
    lookup: "transdigm-group",
  },
  {
    ticker: "TRV",
    company: "Travelers Companies (The)",
    sector: "Financials",
    image: "the-travelers-companies.svg",
    price: "196.26",
    prediction: "buy",
    lookup: "travelers-companies-(the)",
  },
  {
    ticker: "TRMB",
    company: "Trimble Inc.",
    sector: "Information Technology",
    image: "trimble.svg",
    price: "63.44",
    prediction: "buy",
    lookup: "trimble-inc.",
  },
  {
    ticker: "TFC",
    company: "Truist",
    sector: "Financials",
    image: "truist-financial.svg",
    price: "153.49",
    prediction: "sell",
    lookup: "truist",
  },
  {
    ticker: "TYL",
    company: "Tyler Technologies",
    sector: "Information Technology",
    image: "tyler-technologies.svg",
    price: "118.64",
    prediction: "buy",
    lookup: "tyler-technologies",
  },
  {
    ticker: "TSN",
    company: "Tyson Foods",
    sector: "Consumer Staples",
    image: "tyson-foods.svg",
    price: "81.78",
    prediction: "sell",
    lookup: "tyson-foods",
  },
  {
    ticker: "USB",
    company: "U.S. Bank",
    sector: "Financials",
    image: "us-bancorp.svg",
    price: "182.3",
    prediction: "sell",
    lookup: "u.s.-bank",
  },
  {
    ticker: "UDR",
    company: "UDR, Inc.",
    sector: "Real Estate",
    image: "udr-apartments.svg",
    price: "100.8",
    prediction: "buy",
    lookup: "udr,-inc.",
  },
  {
    ticker: "ULTA",
    company: "Ulta Beauty",
    sector: "Consumer Discretionary",
    image: "ulta-beauty.svg",
    price: "118.76",
    prediction: "buy",
    lookup: "ulta-beauty",
  },
  {
    ticker: "UNP",
    company: "Union Pacific Corporation",
    sector: "Industrials",
    image: "union-pacific-corporation.svg",
    price: "161.96",
    prediction: "sell",
    lookup: "union-pacific-corporation",
  },
  {
    ticker: "UAL",
    company: "United Airlines Holdings",
    sector: "Industrials",
    image: "united-airlines.svg",
    price: "128.91",
    prediction: "sell",
    lookup: "united-airlines-holdings",
  },
  {
    ticker: "UPS",
    company: "United Parcel Service",
    sector: "Industrials",
    image: "ups.svg",
    price: "125.84",
    prediction: "buy",
    lookup: "united-parcel-service",
  },
  {
    ticker: "URI",
    company: "United Rentals",
    sector: "Industrials",
    image: "united-rentals.svg",
    price: "73.81",
    prediction: "buy",
    lookup: "united-rentals",
  },
  {
    ticker: "UNH",
    company: "UnitedHealth Group",
    sector: "Health Care",
    image: "united-health.svg",
    price: "188.15",
    prediction: "sell",
    lookup: "unitedhealth-group",
  },
  {
    ticker: "UHS",
    company: "Universal Health Services",
    sector: "Health Care",
    image: "universal-health-services.svg",
    price: "85.32",
    prediction: "sell",
    lookup: "universal-health-services",
  },
  {
    ticker: "VLO",
    company: "Valero Energy",
    sector: "Energy",
    image: "valero.svg",
    price: "178.76",
    prediction: "buy",
    lookup: "valero-energy",
  },
  {
    ticker: "VTR",
    company: "Ventas",
    sector: "Real Estate",
    image: "ventas.svg",
    price: "168.7",
    prediction: "buy",
    lookup: "ventas",
  },
  {
    ticker: "VLTO",
    company: "Veralto",
    sector: "Industrials",
    image: "default.svg",
    price: "44.1",
    prediction: "sell",
    lookup: "veralto",
  },
  {
    ticker: "VRSN",
    company: "Verisign",
    sector: "Information Technology",
    image: "verisign.svg",
    price: "169.71",
    prediction: "buy",
    lookup: "verisign",
  },
  {
    ticker: "VRSK",
    company: "Verisk",
    sector: "Industrials",
    image: "verisk-analytics.svg",
    price: "122.10",
    prediction: "sell",
    lookup: "verisk",
  },
  {
    ticker: "VZ",
    company: "Verizon",
    sector: "Communication Services",
    image: "verizon.svg",
    price: "171.83",
    prediction: "sell",
    lookup: "verizon",
  },
  {
    ticker: "VRTX",
    company: "Vertex Pharmaceuticals",
    sector: "Health Care",
    image: "vertex-pharmaceuticals.svg",
    price: "42.72",
    prediction: "buy",
    lookup: "vertex-pharmaceuticals",
  },
  {
    ticker: "VFC",
    company: "VF Corporation",
    sector: "Consumer Discretionary",
    image: "vf-corp.svg",
    price: "140.8",
    prediction: "buy",
    lookup: "vf-corporation",
  },
  {
    ticker: "VTRS",
    company: "Viatris",
    sector: "Health Care",
    image: "viatris.svg",
    price: "170.86",
    prediction: "sell",
    lookup: "viatris",
  },
  {
    ticker: "VICI",
    company: "Vici Properties",
    sector: "Real Estate",
    image: "vici-properties.svg",
    price: "41.1",
    prediction: "buy",
    lookup: "vici-properties",
  },
  {
    ticker: "V",
    company: "Visa Inc.",
    sector: "Financials",
    image: "visa.svg",
    price: "136.17",
    prediction: "sell",
    lookup: "visa-inc.",
  },
  {
    ticker: "VMC",
    company: "Vulcan Materials Company",
    sector: "Materials",
    image: "vulcan-materials.svg",
    price: "43.40",
    prediction: "sell",
    lookup: "vulcan-materials-company",
  },
  {
    ticker: "WRB",
    company: "Berkley",
    sector: "Financials",
    image: "wr-berkley.svg",
    price: "135.56",
    prediction: "sell",
    lookup: "berkley",
  },
  {
    ticker: "WAB",
    company: "Wabtec",
    sector: "Industrials",
    image: "wabtec.svg",
    price: "70.45",
    prediction: "sell",
    lookup: "wabtec",
  },
  {
    ticker: "WBA",
    company: "Walgreens Boots Alliance",
    sector: "Consumer Staples",
    image: "walgreens-boots-alliance.svg",
    price: "132.49",
    prediction: "sell",
    lookup: "walgreens-boots-alliance",
  },
  {
    ticker: "WMT",
    company: "Walmart",
    sector: "Consumer Staples",
    image: "walmart.svg",
    price: "144.15",
    prediction: "buy",
    lookup: "walmart",
  },
  {
    ticker: "DIS",
    company: "Walt Disney",
    sector: "Communication Services",
    image: "walt-disney.svg",
    price: "181.27",
    prediction: "buy",
    lookup: "walt-disney",
  },
  {
    ticker: "WBD",
    company: "Warner Bros. Discovery",
    sector: "Communication Services",
    image: "warner-bros-discovery.svg",
    price: "100.87",
    prediction: "sell",
    lookup: "warner-bros.-discovery",
  },
  {
    ticker: "WM",
    company: "Waste Management",
    sector: "Industrials",
    image: "waste-management.svg",
    price: "198.2",
    prediction: "buy",
    lookup: "waste-management",
  },
  {
    ticker: "WAT",
    company: "Waters Corporation",
    sector: "Health Care",
    image: "waters-corporation.svg",
    price: "35.99",
    prediction: "sell",
    lookup: "waters-corporation",
  },
  {
    ticker: "WEC",
    company: "WEC Energy Group",
    sector: "Utilities",
    image: "wec-energy.svg",
    price: "74.66",
    prediction: "buy",
    lookup: "wec-energy-group",
  },
  {
    ticker: "WFC",
    company: "Wells Fargo",
    sector: "Financials",
    image: "wells-fargo.svg",
    price: "72.85",
    prediction: "sell",
    lookup: "wells-fargo",
  },
  {
    ticker: "WELL",
    company: "Welltower",
    sector: "Real Estate",
    image: "welltower.svg",
    price: "192.21",
    prediction: "sell",
    lookup: "welltower",
  },
  {
    ticker: "WST",
    company: "West Pharmaceutical Services",
    sector: "Health Care",
    image: "west-pharma.svg",
    price: "118.49",
    prediction: "sell",
    lookup: "west-pharmaceutical-services",
  },
  {
    ticker: "WDC",
    company: "Western Digital",
    sector: "Information Technology",
    image: "western-digital.svg",
    price: "96.40",
    prediction: "sell",
    lookup: "western-digital",
  },
  {
    ticker: "WRK",
    company: "WestRock",
    sector: "Materials",
    image: "westrock.svg",
    price: "90.5",
    prediction: "buy",
    lookup: "westrock",
  },
  {
    ticker: "WY",
    company: "Weyerhaeuser",
    sector: "Real Estate",
    image: "weyerhaeuser.svg",
    price: "127.72",
    prediction: "buy",
    lookup: "weyerhaeuser",
  },
  {
    ticker: "WHR",
    company: "Whirlpool Corporation",
    sector: "Consumer Discretionary",
    image: "whirlpool.svg",
    price: "159.4",
    prediction: "buy",
    lookup: "whirlpool-corporation",
  },
  {
    ticker: "WMB",
    company: "Williams Companies",
    sector: "Energy",
    image: "williams-companies.svg",
    price: "67.36",
    prediction: "buy",
    lookup: "williams-companies",
  },
  {
    ticker: "WTW",
    company: "Willis Towers Watson",
    sector: "Financials",
    image: "willis-wowers-watson.svg",
    price: "187.57",
    prediction: "buy",
    lookup: "willis-towers-watson",
  },
  {
    ticker: "GWW",
    company: "W. W. Grainger",
    sector: "Industrials",
    image: "ww-grainger.svg",
    price: "87.6",
    prediction: "buy",
    lookup: "w.-w.-grainger",
  },
  {
    ticker: "WYNN",
    company: "Wynn Resorts",
    sector: "Consumer Discretionary",
    image: "wynn-resorts.svg",
    price: "60.60",
    prediction: "sell",
    lookup: "wynn-resorts",
  },
  {
    ticker: "XEL",
    company: "Xcel Energy",
    sector: "Utilities",
    image: "xcel-energy.svg",
    price: "161.90",
    prediction: "buy",
    lookup: "xcel-energy",
  },
  {
    ticker: "XYL",
    company: "Xylem Inc.",
    sector: "Industrials",
    image: "xylem.svg",
    price: "163.75",
    prediction: "buy",
    lookup: "xylem-inc.",
  },
  {
    ticker: "YUM",
    company: "Yum! Brands",
    sector: "Consumer Discretionary",
    image: "yum.svg",
    price: "60.73",
    prediction: "sell",
    lookup: "yum!-brands",
  },
  {
    ticker: "ZBRA",
    company: "Zebra Technologies",
    sector: "Information Technology",
    image: "zebra-technologies.svg",
    price: "186.1",
    prediction: "buy",
    lookup: "zebra-technologies",
  },
  {
    ticker: "ZBH",
    company: "Zimmer Biomet",
    sector: "Health Care",
    image: "zimmer-biomet.svg",
    price: "180.8",
    prediction: "buy",
    lookup: "zimmer-biomet",
  },
  {
    ticker: "ZION",
    company: "Zions Bancorporation",
    sector: "Financials",
    image: "zions.svg",
    price: "99.22",
    prediction: "sell",
    lookup: "zions-bancorporation",
  },
  {
    ticker: "ZTS",
    company: "Zoetis",
    sector: "Health Care",
    image: "zoetis.svg",
    price: "58.46",
    prediction: "sell",
    lookup: "zoetis",
  },
];
